#!/usr/bin/env python3
"""
Architecture Diagram: e2e-conductor-test
Azure Static Web App with CDN

Generated by azure-diagrams skill | 2026-02-05
Based on 02-architecture-assessment.md
"""

from diagrams import Diagram, Cluster, Edge
from diagrams.azure.web import StaticApps
from diagrams.azure.network import CDNProfiles, FrontDoors
from diagrams.azure.monitor import LogAnalyticsWorkspaces, Monitor
from diagrams.azure.devops import Pipelines
from diagrams.azure.security import KeyVaults
from diagrams.generic.device import Mobile, Tablet
from diagrams.onprem.client import Users
from diagrams.onprem.vcs import Github

# Diagram configuration
graph_attr = {
    "fontsize": "16",
    "bgcolor": "white",
    "pad": "0.5",
    "nodesep": "0.8",
    "ranksep": "1.0",
}

with Diagram(
    "e2e-conductor-test: Azure Static Web App with CDN",
    filename="agent-output/e2e-conductor-test/03-des-diagram",
    show=False,
    direction="TB",
    graph_attr=graph_attr,
    outformat="png",
):
    # External Users
    with Cluster("Internet Users"):
        users = Users("Global Users")
        mobile = Mobile("Mobile")
        tablet = Tablet("Tablet")

    # Azure CDN - Global Edge
    with Cluster("Azure CDN (Standard Microsoft)"):
        cdn = CDNProfiles("CDN Endpoint\nwesteurope")
        cdn_label = "Global edge caching\nHTTPS enforcement"

    # Static Web App
    with Cluster("Azure Static Web App\n(Free Tier - westeurope)"):
        swa = StaticApps("Static Web App\ne2e-conductor-test")
        swa_features = """
        • Free tier
        • Managed SSL
        • Preview environments
        """

    # Monitoring & Alerting
    with Cluster("Monitoring & Alerting"):
        logs = LogAnalyticsWorkspaces("Log Analytics\n(Free tier)")
        monitor = Monitor("Metric Alerts\n(CDN Health)")

    # CI/CD Pipeline
    with Cluster("CI/CD"):
        github = Github("GitHub Repo")
        actions = Pipelines("GitHub Actions")

    # Data Flow: Users -> CDN -> Static Web App
    [users, mobile, tablet] >> Edge(label="HTTPS", color="green") >> cdn

    # CDN to Origin
    cdn >> Edge(label="Origin Request\n(cache miss)", style="dashed") >> swa

    # Monitoring connections
    cdn >> Edge(label="Logs", style="dotted", color="blue") >> logs
    swa >> Edge(label="Logs", style="dotted", color="blue") >> logs
    logs >> Edge(label="Alerts", color="orange") >> monitor

    # CI/CD Flow
    github >> Edge(label="Push to main") >> actions
    actions >> Edge(label="Deploy", color="purple") >> swa

print("✅ Diagram generated: agent-output/e2e-conductor-test/03-des-diagram.png")
