"""
Contoso Service Hub — Proposed Architecture Diagram

Generated by design agent | 2026-03-16

Prerequisites:
    pip install diagrams pillow
    apt-get install -y graphviz

Usage:
    /workspaces/azure-agentic-infraops/.venv/bin/python agent-output/contoso-service-hub-run-1/03-des-diagram.py

Output:
    agent-output/contoso-service-hub-run-1/03-des-diagram.png
"""

import os

from diagrams import Cluster, Diagram, Edge
from diagrams.azure.compute import AKS, Disks, VM
from diagrams.azure.database import CacheForRedis, DatabaseForPostgresqlServers
from diagrams.azure.identity import ExternalIdentities, ManagedIdentities
from diagrams.azure.integration import APIManagement
from diagrams.azure.monitor import ApplicationInsights, LogAnalyticsWorkspaces, Monitor
from diagrams.azure.network import Firewall, FrontDoors, LoadBalancers, PrivateEndpoint, Subnets, VirtualNetworks
from diagrams.azure.security import KeyVaults
from diagrams.azure.storage import AzureFileshares, BlobStorage
from diagrams.onprem.client import Users
from diagrams.onprem.vcs import Github


OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "03-des-diagram")

graph_attr = {
    "bgcolor": "white",
    "pad": "0.8",
    "nodesep": "0.95",
    "ranksep": "1.0",
    "splines": "spline",
    "fontname": "Arial Bold",
    "fontsize": "16",
    "dpi": "160",
    "label": "Contoso Service Hub — Design Topology\nswedencentral | Hub-Spoke | Private Data Plane | Bicep",
    "labelloc": "t",
    "labeljust": "c",
}

node_attr = {
    "fontname": "Arial Bold",
    "fontsize": "11",
    "labelloc": "t",
}

edge_attr = {
    "fontname": "Arial",
    "fontsize": "9",
}

cluster_style = {
    "margin": "30",
    "fontname": "Arial Bold",
    "fontsize": "14",
}

EDGE_USER = {"style": "bold", "color": "#0078D4", "penwidth": "2.0"}
EDGE_APP = {"style": "solid", "color": "#333333", "penwidth": "1.5"}
EDGE_SECRET = {"style": "dashed", "color": "#C00000", "penwidth": "1.5"}
EDGE_TELEMETRY = {"style": "dotted", "color": "#8764B8", "penwidth": "1.5"}
EDGE_DEVOPS = {"style": "dashed", "color": "#FF8C00", "penwidth": "1.5"}


with Diagram(
    "",
    show=False,
    filename=OUTPUT_FILE,
    outformat="png",
    direction="LR",
    graph_attr=graph_attr,
    node_attr=node_attr,
    edge_attr=edge_attr,
):
    n_user_channels = Users("Residents\nVisitors\nTenants\nStaff")

    with Cluster(
        "External Identity & Delivery Boundary",
        graph_attr={**cluster_style, "bgcolor": "#F8F9FA", "style": "rounded"},
    ):
        n_id_entra_external = ExternalIdentities("Entra External ID\n15K MAU CIAM")
        n_edge_front_door = FrontDoors("Front Door Premium\nGlobal edge + CDN")
        n_edge_waf = Firewall("WAF Policy\nOWASP + custom rules")
        n_devops_github = Github("GitHub Enterprise\nCI/CD + source control")

    with Cluster(
        "Azure Subscription Boundary\nrg-contoso-service-hub-prod",
        graph_attr={**cluster_style, "bgcolor": "#F0F8FF", "style": "rounded"},
    ):
        with Cluster(
            "Observability Boundary",
            graph_attr={**cluster_style, "bgcolor": "#F3E8FD", "style": "rounded"},
        ):
            n_ops_monitor = Monitor("Azure Monitor\nAlerts + workbooks")
            n_ops_app_insights = ApplicationInsights("Application Insights\nDistributed tracing")
            n_ops_log_analytics = LogAnalyticsWorkspaces("Log Analytics\n90-day retention")

        with Cluster(
            "Hub Network Boundary\nVNet 10.40.0.0/16",
            graph_attr={**cluster_style, "bgcolor": "#E0F2F1", "style": "rounded"},
        ):
            n_net_vnet = VirtualNetworks("Hub-Spoke VNet\n10.40.0.0/16")

            with Cluster(
                "Ingress Subnet\n10.40.1.0/24",
                graph_attr={**cluster_style, "bgcolor": "#E6F4EA", "style": "rounded"},
            ):
                n_net_ingress = Subnets("Ingress Subnet\nAPIM private ingress")
                n_api_apim = APIManagement("APIM Premium v2\nZone-redundant")
                n_net_lb = LoadBalancers("Internal Load Balancer\nAPIM to AKS")

            with Cluster(
                "Private Endpoint Subnet\n10.40.2.0/24",
                graph_attr={**cluster_style, "bgcolor": "#FFF9C4", "style": "rounded"},
            ):
                n_pe_postgres = PrivateEndpoint("PE: PostgreSQL")
                n_pe_redis = PrivateEndpoint("PE: Redis")
                n_pe_blob = PrivateEndpoint("PE: Blob")
                n_pe_files = PrivateEndpoint("PE: Azure Files")
                n_pe_key_vault = PrivateEndpoint("PE: Key Vault")

            with Cluster(
                "Management Subnet\n10.40.3.0/24",
                graph_attr={**cluster_style, "bgcolor": "#FFF3E0", "style": "rounded"},
            ):
                n_vm_management = VM("D8s v5 VM\nMgmt / build host")

        with Cluster(
            "Application Spoke Boundary\nPrivate compute plane",
            graph_attr={**cluster_style, "bgcolor": "#E8F0FE", "style": "rounded"},
        ):
            n_app_aks = AKS("AKS private cluster\n3 AZ | 3 user nodes")
            n_app_identity = ManagedIdentities("Managed identities\nWorkload + node")
            n_app_disks = Disks("Managed Disks\nPremium SSD")

        with Cluster(
            "Private Data Services Boundary\npublicNetworkAccess: Disabled",
            graph_attr={**cluster_style, "bgcolor": "#FCE4EC", "style": "rounded,dashed"},
        ):
            n_data_postgres = DatabaseForPostgresqlServers("PostgreSQL Flex\nZR HA | 256 GB")
            n_data_redis = CacheForRedis("Managed Redis M100\n128 GB")
            n_data_blob = BlobStorage("Blob Storage\nHot tier")
            n_data_files = AzureFileshares("Azure Files\nPremium SSD")
            n_sec_key_vault = KeyVaults("Key Vault\nRBAC + purge protect")

    n_user_channels >> Edge(label="HTTPS", **EDGE_USER) >> n_edge_front_door
    n_edge_front_door >> Edge(label="WAF inspection", **EDGE_USER) >> n_edge_waf
    n_edge_waf >> Edge(label="Private origin", **EDGE_USER) >> n_api_apim

    n_user_channels >> Edge(label="OIDC / sign-in", **EDGE_USER) >> n_id_entra_external
    n_id_entra_external >> Edge(label="JWT / claims", **EDGE_USER) >> n_api_apim

    n_net_vnet >> Edge(label="contains", **EDGE_APP) >> [n_net_ingress, n_vm_management]
    n_net_vnet >> Edge(label="hosts", **EDGE_APP) >> [n_pe_postgres, n_pe_redis, n_pe_blob, n_pe_files, n_pe_key_vault]

    n_api_apim >> Edge(label="private east-west", **EDGE_APP) >> n_net_lb
    n_net_lb >> Edge(label="ingress", **EDGE_APP) >> n_app_aks

    n_app_aks >> Edge(label="CSI / PV", **EDGE_APP) >> n_app_disks
    n_app_aks >> Edge(label="AAD workload auth", **EDGE_USER) >> n_app_identity
    n_app_aks >> Edge(label="secrets", **EDGE_SECRET) >> n_sec_key_vault
    n_app_identity >> Edge(label="RBAC", **EDGE_SECRET) >> n_sec_key_vault

    n_app_aks >> Edge(label="SQL", **EDGE_APP) >> n_pe_postgres
    n_app_aks >> Edge(label="cache", **EDGE_APP) >> n_pe_redis
    n_app_aks >> Edge(label="objects", **EDGE_APP) >> n_pe_blob
    n_app_aks >> Edge(label="shared files", **EDGE_APP) >> n_pe_files
    n_app_aks >> Edge(label="vault", **EDGE_APP) >> n_pe_key_vault

    n_pe_postgres >> Edge(label="TLS 1.2", **EDGE_APP) >> n_data_postgres
    n_pe_redis >> Edge(label="private access", **EDGE_APP) >> n_data_redis
    n_pe_blob >> Edge(label="private access", **EDGE_APP) >> n_data_blob
    n_pe_files >> Edge(label="private access", **EDGE_APP) >> n_data_files
    n_pe_key_vault >> Edge(label="private access", **EDGE_APP) >> n_sec_key_vault

    n_devops_github >> Edge(label="actions / gitops", **EDGE_DEVOPS) >> n_vm_management
    n_devops_github >> Edge(label="deployments", **EDGE_DEVOPS) >> n_app_aks

    [n_api_apim, n_app_aks, n_vm_management] >> Edge(label="telemetry", **EDGE_TELEMETRY) >> n_ops_app_insights
    [n_data_postgres, n_data_redis, n_data_blob, n_data_files, n_sec_key_vault] >> Edge(label="diagnostics", **EDGE_TELEMETRY) >> n_ops_monitor
    n_ops_app_insights >> Edge(label="workspace-based", **EDGE_TELEMETRY) >> n_ops_log_analytics
    n_ops_monitor >> Edge(label="logs + alerts", **EDGE_TELEMETRY) >> n_ops_log_analytics

print(f"Diagram saved to: {OUTPUT_FILE}.png")
