"""
Contoso Service Hub — Deployment Dependency Diagram

Generated by bicep-plan agent | 2026-03-16

Prerequisites:
    pip install diagrams pillow
    apt-get install -y graphviz

Usage:
    /workspaces/azure-agentic-infraops/.venv/bin/python agent-output/contoso-service-hub-run-1/04-dependency-diagram.py

Output:
    agent-output/contoso-service-hub-run-1/04-dependency-diagram.png
"""

import os

from diagrams import Cluster, Diagram, Edge
from diagrams.azure.compute import AKS, Disks, VM
from diagrams.azure.database import CacheForRedis, DatabaseForPostgresqlServers
from diagrams.azure.identity import ManagedIdentities
from diagrams.azure.integration import APIManagement
from diagrams.azure.monitor import ApplicationInsights, LogAnalyticsWorkspaces
from diagrams.azure.network import FrontDoors, VirtualNetworks
from diagrams.azure.security import KeyVaults
from diagrams.azure.storage import BlobStorage
from diagrams.generic.blank import Blank

OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "04-dependency-diagram")

graph_attr = {
    "bgcolor": "white",
    "pad": "0.8",
    "nodesep": "0.8",
    "ranksep": "1.2",
    "splines": "spline",
    "fontname": "Arial Bold",
    "fontsize": "16",
    "dpi": "160",
    "label": (
        "Contoso Service Hub — Deployment Dependency Graph\n"
        "Phased: Foundation → Data → Edge → Platform"
    ),
    "labelloc": "t",
    "labeljust": "c",
}

node_attr = {
    "fontname": "Arial Bold",
    "fontsize": "10",
    "labelloc": "t",
}

edge_attr = {
    "fontname": "Arial",
    "fontsize": "8",
}

cluster_style = {
    "margin": "25",
    "fontname": "Arial Bold",
    "fontsize": "13",
}

EDGE_DEPENDS = {"style": "solid", "color": "#333333", "penwidth": "1.5"}
EDGE_PHASE = {"style": "dashed", "color": "#0078D4", "penwidth": "2.0"}

with Diagram(
    "",
    show=False,
    filename=OUTPUT_FILE,
    outformat="png",
    direction="TB",
    graph_attr=graph_attr,
    node_attr=node_attr,
    edge_attr=edge_attr,
):
    # Phase 1: Foundation
    with Cluster(
        "Phase 1: Foundation (~15 min)",
        graph_attr={**cluster_style, "bgcolor": "#E8F5E9", "style": "rounded"},
    ):
        n_monitoring = LogAnalyticsWorkspaces("monitoring.bicep\nLog Analytics\n+ App Insights")
        n_budget = Blank("budget.bicep\nConsumption Budget")
        n_networking = VirtualNetworks("networking.bicep\nVNet + Subnets\n+ NSGs + DNS Zones")
        n_keyvault = KeyVaults("keyvault.bicep\nKey Vault + PE")

    # Phase 2: Data
    with Cluster(
        "Phase 2: Data (~25 min)",
        graph_attr={**cluster_style, "bgcolor": "#E3F2FD", "style": "rounded"},
    ):
        n_postgresql = DatabaseForPostgresqlServers("postgresql.bicep\nPostgreSQL Flex\nHA + PE")
        n_redis = CacheForRedis("redis.bicep\nManaged Redis\nM100 + PE")
        n_storage = BlobStorage("storage.bicep\nBlob + Files\n+ Disks + PEs")

    # Phase 3: Edge
    with Cluster(
        "Phase 3: Edge (~30 min)",
        graph_attr={**cluster_style, "bgcolor": "#FFF3E0", "style": "rounded"},
    ):
        n_apim = APIManagement("apim.bicep\nAPIM Premium v2\nVNet integrated")
        n_waf = FrontDoors("waf.bicep\nFront Door Premium\n+ WAF Policy")
        n_identity = ManagedIdentities("identity.bicep\nRole Assignments\n+ Workload Identity")

    # Phase 4: Platform
    with Cluster(
        "Phase 4: Platform (~20 min)",
        graph_attr={**cluster_style, "bgcolor": "#F3E5F5", "style": "rounded"},
    ):
        n_aks = AKS("aks.bicep\nAKS Private Cluster\n3-AZ User Nodes")
        n_vm = VM("vm.bicep\nD8s v5 Mgmt VM")

    # Phase 1 internal dependencies
    n_networking << Edge(**EDGE_DEPENDS, label="diagnostics") << n_monitoring
    n_keyvault << Edge(**EDGE_DEPENDS, label="PE subnet") << n_networking

    # Phase 2 dependencies on Phase 1
    n_postgresql << Edge(**EDGE_DEPENDS, label="PE + logs") << n_networking
    n_postgresql << Edge(**EDGE_DEPENDS, label="secrets") << n_keyvault
    n_postgresql << Edge(**EDGE_DEPENDS, label="diagnostics") << n_monitoring

    n_redis << Edge(**EDGE_DEPENDS, label="PE + logs") << n_networking
    n_redis << Edge(**EDGE_DEPENDS, label="diagnostics") << n_monitoring

    n_storage << Edge(**EDGE_DEPENDS, label="PE + logs") << n_networking
    n_storage << Edge(**EDGE_DEPENDS, label="secrets") << n_keyvault
    n_storage << Edge(**EDGE_DEPENDS, label="diagnostics") << n_monitoring

    # Phase 3 dependencies
    n_apim << Edge(**EDGE_DEPENDS, label="VNet + PE") << n_networking
    n_apim << Edge(**EDGE_DEPENDS, label="certs") << n_keyvault
    n_apim << Edge(**EDGE_DEPENDS, label="diagnostics") << n_monitoring

    n_waf << Edge(**EDGE_DEPENDS, label="origin") << n_apim

    n_identity << Edge(**EDGE_DEPENDS, label="role target") << n_keyvault
    n_identity << Edge(**EDGE_DEPENDS, label="role target") << n_storage
    n_identity << Edge(**EDGE_DEPENDS, label="role target") << n_redis

    # Phase 4 dependencies
    n_aks << Edge(**EDGE_DEPENDS, label="AKS subnet") << n_networking
    n_aks << Edge(**EDGE_DEPENDS, label="secrets") << n_keyvault
    n_aks << Edge(**EDGE_DEPENDS, label="diagnostics") << n_monitoring
    n_aks << Edge(**EDGE_DEPENDS, label="workload identity") << n_identity

    n_vm << Edge(**EDGE_DEPENDS, label="mgmt subnet") << n_networking
    n_vm << Edge(**EDGE_DEPENDS, label="secrets") << n_keyvault
    n_vm << Edge(**EDGE_DEPENDS, label="diagnostics") << n_monitoring
