"""
Contoso Service Hub — Runtime Data Flow Diagram

Generated by bicep-plan agent | 2026-03-16

Prerequisites:
    pip install diagrams pillow
    apt-get install -y graphviz

Usage:
    /workspaces/azure-agentic-infraops/.venv/bin/python agent-output/contoso-service-hub-run-1/04-runtime-diagram.py

Output:
    agent-output/contoso-service-hub-run-1/04-runtime-diagram.png
"""

import os

from diagrams import Cluster, Diagram, Edge
from diagrams.azure.compute import AKS, VM
from diagrams.azure.database import CacheForRedis, DatabaseForPostgresqlServers
from diagrams.azure.identity import ExternalIdentities, ManagedIdentities
from diagrams.azure.integration import APIManagement
from diagrams.azure.monitor import ApplicationInsights, LogAnalyticsWorkspaces
from diagrams.azure.network import FrontDoors, PrivateEndpoint, VirtualNetworks
from diagrams.azure.security import KeyVaults
from diagrams.azure.storage import AzureFileshares, BlobStorage
from diagrams.onprem.client import Users

OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "04-runtime-diagram")

graph_attr = {
    "bgcolor": "white",
    "pad": "0.8",
    "nodesep": "0.9",
    "ranksep": "1.0",
    "splines": "spline",
    "fontname": "Arial Bold",
    "fontsize": "16",
    "dpi": "160",
    "label": (
        "Contoso Service Hub — Runtime Data Flow\n"
        "swedencentral | Private Data Plane | Zero Trust"
    ),
    "labelloc": "t",
    "labeljust": "c",
}

node_attr = {
    "fontname": "Arial Bold",
    "fontsize": "10",
    "labelloc": "t",
}

edge_attr = {
    "fontname": "Arial",
    "fontsize": "8",
}

cluster_style = {
    "margin": "25",
    "fontname": "Arial Bold",
    "fontsize": "13",
}

EDGE_USER = {"style": "bold", "color": "#0078D4", "penwidth": "2.0"}
EDGE_AUTH = {"style": "dashed", "color": "#E65100", "penwidth": "1.5"}
EDGE_DATA = {"style": "solid", "color": "#333333", "penwidth": "1.5"}
EDGE_SECRET = {"style": "dashed", "color": "#C00000", "penwidth": "1.5"}
EDGE_TELEMETRY = {"style": "dotted", "color": "#8764B8", "penwidth": "1.2"}
EDGE_PE = {"style": "solid", "color": "#00695C", "penwidth": "1.2"}

with Diagram(
    "",
    show=False,
    filename=OUTPUT_FILE,
    outformat="png",
    direction="LR",
    graph_attr=graph_attr,
    node_attr=node_attr,
    edge_attr=edge_attr,
):
    n_users = Users("Residents\nVisitors\nTenants")

    # External identity layer
    with Cluster(
        "Identity & Edge Boundary",
        graph_attr={**cluster_style, "bgcolor": "#FFF8E1", "style": "rounded"},
    ):
        n_entra = ExternalIdentities("Entra External ID\n15K MAU CIAM")
        n_frontdoor = FrontDoors("Front Door Premium\nWAF + CDN\nOWASP 3.2")

    # Azure subscription boundary
    with Cluster(
        "Azure Subscription — swedencentral\nrg-contoso-service-hub-prod",
        graph_attr={**cluster_style, "bgcolor": "#F0F8FF", "style": "rounded"},
    ):
        # Observability
        with Cluster(
            "Observability",
            graph_attr={**cluster_style, "bgcolor": "#F3E8FD", "style": "rounded"},
        ):
            n_appinsights = ApplicationInsights("App Insights\nTracing")
            n_loganalytics = LogAnalyticsWorkspaces("Log Analytics\n90-day retention")

        # Ingress
        with Cluster(
            "Ingress Layer\nsnet-apim",
            graph_attr={**cluster_style, "bgcolor": "#E8F5E9", "style": "rounded"},
        ):
            n_apim = APIManagement("APIM Premium v2\nJWT validation\nX-Azure-FDID check")

        # Compute
        with Cluster(
            "Compute Layer\nsnet-aks (10.40.0.0/22)",
            graph_attr={**cluster_style, "bgcolor": "#E3F2FD", "style": "rounded"},
        ):
            n_aks = AKS("AKS Private Cluster\n3×D8s v5 (3-AZ)\nWorkload Identity")
            n_identity = ManagedIdentities("Workload Identity\nFederated Credentials")

        # Data layer (all via private endpoints)
        with Cluster(
            "Data Layer (Private Endpoints)\nsnet-data (10.40.4.0/24)",
            graph_attr={**cluster_style, "bgcolor": "#FCE4EC", "style": "rounded"},
        ):
            n_pe = PrivateEndpoint("Private\nEndpoints ×5")
            n_postgresql = DatabaseForPostgresqlServers("PostgreSQL Flex\nGP D4s v5\nHA, 256 GB")
            n_redis = CacheForRedis("Managed Redis\nM100 (128 GB)\nEntra auth")
            n_blob = BlobStorage("Blob Storage\n200 GB\nNo public access")
            n_files = AzureFileshares("Azure Files\nPremium 256 GiB")
            n_keyvault = KeyVaults("Key Vault\nSecrets + Certs\nPurge protected")

        # Management
        with Cluster(
            "Management\nsnet-mgmt",
            graph_attr={**cluster_style, "bgcolor": "#EFEBE9", "style": "rounded"},
        ):
            n_vm = VM("Mgmt VM\nD8s v5\nSystem MI")

    # === User request flow (blue) ===
    n_users >> Edge(**EDGE_USER, label="HTTPS") >> n_frontdoor
    n_frontdoor >> Edge(**EDGE_USER, label="origin\nPrivate Link") >> n_apim
    n_apim >> Edge(**EDGE_USER, label="internal LB") >> n_aks

    # === Authentication flow (orange) ===
    n_users >> Edge(**EDGE_AUTH, label="OAuth 2.0\nOIDC") >> n_entra
    n_entra >> Edge(**EDGE_AUTH, label="JWT token") >> n_frontdoor

    # === Secret flow (red dashed) ===
    n_aks >> Edge(**EDGE_SECRET, label="workload\nidentity") >> n_identity
    n_identity >> Edge(**EDGE_SECRET, label="secrets via PE") >> n_keyvault

    # === Data flows via private endpoints (green/dark) ===
    n_aks >> Edge(**EDGE_PE, label="queries\nEntra auth") >> n_pe
    n_pe >> Edge(**EDGE_PE, label="PostgreSQL\nwire protocol") >> n_postgresql
    n_pe >> Edge(**EDGE_PE, label="Redis\nprotocol") >> n_redis
    n_pe >> Edge(**EDGE_PE, label="HTTPS\nblob ops") >> n_blob
    n_pe >> Edge(**EDGE_PE, label="SMB 3.0") >> n_files

    # === Telemetry flows (purple dotted) ===
    n_aks >> Edge(**EDGE_TELEMETRY, label="OMS agent") >> n_loganalytics
    n_apim >> Edge(**EDGE_TELEMETRY, label="diagnostics") >> n_appinsights
    n_postgresql >> Edge(**EDGE_TELEMETRY, label="diagnostics") >> n_loganalytics
    n_redis >> Edge(**EDGE_TELEMETRY, label="diagnostics") >> n_loganalytics
    n_frontdoor >> Edge(**EDGE_TELEMETRY, label="access logs") >> n_loganalytics

    # === Management flow ===
    n_vm >> Edge(style="dashed", color="#795548", label="kubectl\nvia private API") >> n_aks
