// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/terraform-search-import/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "terraform import",
  "How do I terraform import?",
  "Terraform import now",
  "terraform import for my project",
  "import Azure resources",
  "How do I import Azure resources?",
  "Import Azure resources now",
  "import Azure resources for my project",
  "bring unmanaged infra under Terraform",
  "How do I bring unmanaged infra under Terraform?",
  "Bring unmanaged infra under Terraform now",
  "bring unmanaged infra under Terraform for my project",
  "adopt Terraform for existing resources",
  "How do I adopt Terraform for existing resources?",
  "Adopt Terraform for existing resources now",
  "adopt Terraform for existing resources for my project",
  "generate import blocks",
  "How do I generate import blocks?",
  "Generate import blocks now",
  "generate import blocks for my project",
  "importing Azure resources",
  "How do I importing Azure resources?",
  "Importing Azure resources now",
  "importing Azure resources for my project",
  "audit",
  "How do I audit?",
  "Audit now",
  "audit for my project",
  "migration to IaC",
  "How do I migration to IaC?",
  "Migration to IaC now",
  "migration to IaC for my project",
  "bulk import",
  "How do I bulk import?",
  "Bulk import now",
  "bulk import for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "Bicep code",
  "How do I bicep code?",
  "new resource creation",
  "How do I new resource creation?",
  "architecture decisions",
  "How do I architecture decisions?",
  "use azure-bicep-patterns",
  "run azure-bicep-patterns",
  "use terraform-patterns",
  "run terraform-patterns",
  "use azure-adr",
  "run azure-adr",
  "What is the weather today?",
  "Help me write a poem",
];
