// ============================================================================
// Main Bicep Template - e2e-conductor-test
// ============================================================================
// Purpose: E2E validation of 7-step orchestration workflow
// Scope: Subscription-level deployment
// Generated by: bicep-code agent | 2026-02-05
// ============================================================================

targetScope = 'subscription'

// ============================================================================
// Parameters
// ============================================================================

@description('Project identifier for resource naming')
param projectName string = 'e2e-conductor-test'

@description('Environment name (dev/staging/prod)')
@allowed([
  'dev'
  'staging'
  'prod'
])
param environment string = 'dev'

@description('Primary Azure region for deployment')
@allowed([
  'westeurope'
  'eastus2'
  'centralus'
  'westus2'
  'eastasia'
])
param location string = 'westeurope'

@description('Owner for resource tagging (required for governance)')
param owner string

@description('Technical contact email for alerts')
param technicalContact string

@description('Cost center code for billing allocation')
param costCenter string = 'IT-001'

@description('Enable CDN deployment (optional - SWA has built-in global distribution)')
param enableCdn bool = false

// ============================================================================
// Variables
// ============================================================================

// Generate unique suffix for globally unique resource names
var uniqueSuffix = uniqueString(subscription().subscriptionId, projectName, environment)

// CAF-compliant resource naming
var resourceGroupName = 'rg-${projectName}-${environment}-weu'
var staticWebAppName = 'stapp-${take(projectName, 10)}-${environment}'
var cdnProfileName = 'cdn-${projectName}-${environment}'
var cdnEndpointName = 'cdnep-${take(projectName, 8)}-${take(uniqueSuffix, 8)}'
var logAnalyticsName = 'log-${projectName}-${environment}'
var actionGroupName = 'ag-${projectName}-${environment}'
var metricAlertName = 'alert-${projectName}-cdn-health'

// Required tags from governance policy (9 tags enforced)
var requiredTags = {
  environment: environment
  owner: owner
  costcenter: costCenter
  application: projectName
  workload: 'web'
  sla: '99.9%'
  'backup-policy': 'none'
  'maint-window': 'weekends'
  'technical-contact': technicalContact
}

// ============================================================================
// Resource Group Deployment
// ============================================================================

module resourceGroup 'modules/resource-group.bicep' = {
  name: 'deploy-rg-${projectName}'
  params: {
    resourceGroupName: resourceGroupName
    location: location
    tags: requiredTags
  }
}

// ============================================================================
// Static Web App Deployment
// ============================================================================

module staticWebApp 'modules/static-web-app.bicep' = {
  name: 'deploy-stapp-${projectName}'
  scope: az.resourceGroup(subscription().subscriptionId, resourceGroupName)
  params: {
    staticWebAppName: staticWebAppName
    location: location
    tags: requiredTags
  }
  dependsOn: [
    resourceGroup
  ]
}

// ============================================================================
// CDN Deployment (Optional - Standard_Microsoft is deprecated)
// ============================================================================
// Note: Azure CDN with Standard_Microsoft SKU no longer accepts new profiles.
// Static Web Apps include built-in global edge distribution.
// Set enableCdn=true only if you have an existing CDN requirement.

module cdn 'modules/cdn.bicep' = if (enableCdn) {
  name: 'deploy-cdn-${projectName}'
  scope: az.resourceGroup(subscription().subscriptionId, resourceGroupName)
  params: {
    cdnProfileName: cdnProfileName
    cdnEndpointName: cdnEndpointName
    staticWebAppHostname: staticWebApp.outputs.defaultHostname
    tags: requiredTags
  }
  dependsOn: [
    resourceGroup
  ]
}

// ============================================================================
// Monitoring Deployment
// ============================================================================

module monitoring 'modules/monitoring.bicep' = {
  name: 'deploy-monitoring-${projectName}'
  scope: az.resourceGroup(subscription().subscriptionId, resourceGroupName)
  params: {
    logAnalyticsName: logAnalyticsName
    actionGroupName: actionGroupName
    metricAlertName: metricAlertName
    technicalContact: technicalContact
    cdnProfileId: enableCdn ? cdn.outputs.cdnProfileId : ''
    enableCdnAlerts: enableCdn
    tags: requiredTags
  }
  dependsOn: [
    resourceGroup
  ]
}

// ============================================================================
// Outputs
// ============================================================================

@description('Resource group name')
output resourceGroupName string = resourceGroupName

@description('Static Web App default hostname')
output staticWebAppHostname string = staticWebApp.outputs.defaultHostname

@description('CDN endpoint hostname (empty if CDN disabled)')
output cdnEndpointHostname string = enableCdn
  ? cdn.outputs.cdnEndpointHostname
  : 'CDN disabled - using SWA built-in distribution'

@description('Log Analytics workspace ID')
output logAnalyticsWorkspaceId string = monitoring.outputs.logAnalyticsWorkspaceId

@description('Deployment summary')
output summary object = {
  projectName: projectName
  environment: environment
  region: location
  resourceGroup: resourceGroupName
  staticWebApp: staticWebApp.outputs.defaultHostname
  cdnEnabled: enableCdn
  cdnEndpoint: enableCdn ? cdn.outputs.cdnEndpointHostname : 'N/A - SWA built-in distribution'
  monitoring: 'enabled'
  estimatedMonthlyCost: enableCdn ? '$5.10' : '$0.10'
}
