// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/vendor-prompting/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "claude prompting",
  "How do I claude prompting?",
  "Claude prompting now",
  "claude prompting for my project",
  "gpt-5.5 prompting",
  "How do I gpt-5.5 prompting?",
  "Gpt-5.5 prompting now",
  "gpt-5.5 prompting for my project",
  "audit agent",
  "How do I audit agent?",
  "Audit agent now",
  "audit agent for my project",
  "review prompt",
  "How do I review prompt?",
  "Review prompt now",
  "review prompt for my project",
  "vendor best practices",
  "How do I vendor best practices?",
  "Vendor best practices now",
  "vendor best practices for my project",
  "anthropic best practices",
  "How do I anthropic best practices?",
  "Anthropic best practices now",
  "anthropic best practices for my project",
  "openai prompting",
  "How do I openai prompting?",
  "Openai prompting now",
  "openai prompting for my project",
  "authoring or auditing .agent.md / .prompt.md files; verifying vendor-specific patterns ; investigating lint:vendor-prompting findings",
  "How do I authoring or auditing .agent.md / .prompt.md files; verifying vendor-specific patterns ; investigating lint:vendor-prompting findings?",
  "Authoring or auditing .agent.md / .prompt.md files; verifying vendor-specific patterns ; investigating lint:vendor-prompting findings now",
  "authoring or auditing .agent.md / .prompt.md files; verifying vendor-specific patterns ; investigating lint:vendor-prompting findings for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "routine prompt edits where rules are already known",
  "How do I routine prompt edits where rules are already known?",
  "generic markdown style",
  "How do I generic markdown style?",
  "What is the weather today?",
  "Help me write a poem",
];
