// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/terraform-patterns/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "hub-spoke Terraform",
  "How do I hub-spoke Terraform?",
  "Hub-spoke Terraform now",
  "hub-spoke Terraform for my project",
  "private endpoint module",
  "How do I private endpoint module?",
  "Private endpoint module now",
  "private endpoint module for my project",
  "AVM-TF composition",
  "How do I AVM-TF composition?",
  "AVM-TF composition now",
  "AVM-TF composition for my project",
  "diagnostic settings",
  "How do I diagnostic settings?",
  "Diagnostic settings now",
  "diagnostic settings for my project",
  "plan interpretation",
  "How do I plan interpretation?",
  "Plan interpretation now",
  "plan interpretation for my project",
  "Terraform template design",
  "How do I terraform template design?",
  "Terraform template design now",
  "Terraform template design for my project",
  "hub-spoke networking",
  "How do I hub-spoke networking?",
  "Hub-spoke networking now",
  "hub-spoke networking for my project",
  "AVM modules",
  "How do I AVM modules?",
  "AVM modules now",
  "AVM modules for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "Bicep code",
  "How do I bicep code?",
  "architecture decisions",
  "How do I architecture decisions?",
  "troubleshooting",
  "How do I troubleshooting?",
  "diagram generation",
  "How do I diagram generation?",
  "use azure-bicep-patterns",
  "run azure-bicep-patterns",
  "use azure-adr",
  "run azure-adr",
  "use drawio",
  "run drawio",
  "What is the weather today?",
  "Help me write a poem",
];
