// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/iac-common/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "phased deployment",
  "How do I phased deployment?",
  "Phased deployment now",
  "phased deployment for my project",
  "circuit breaker",
  "How do I circuit breaker?",
  "Circuit breaker now",
  "circuit breaker for my project",
  "deploy strategy",
  "How do I deploy strategy?",
  "Deploy strategy now",
  "deploy strategy for my project",
  "deploy issue",
  "How do I deploy issue?",
  "Deploy issue now",
  "deploy issue for my project",
  "shared IaC pattern",
  "How do I shared IaC pattern?",
  "Shared IaC pattern now",
  "shared IaC pattern for my project",
  "circuit breaker patterns",
  "How do I circuit breaker patterns?",
  "Circuit breaker patterns now",
  "circuit breaker patterns for my project",
  "deploy-specific known issues",
  "How do I deploy-specific known issues?",
  "Deploy-specific known issues now",
  "deploy-specific known issues for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "preflight validation",
  "How do I preflight validation?",
  "code generation",
  "How do I code generation?",
  "use azure-validate",
  "run azure-validate",
  "use azure-bicep-patterns",
  "run azure-bicep-patterns",
  "What is the weather today?",
  "Help me write a poem",
];
