"""Contoso Service Hub design architecture diagram.

Generated by design agent | 2026-03-17

Prerequisites:
    pip install diagrams pillow
    apt-get install -y graphviz

Usage:
    /workspaces/azure-agentic-infraops/.venv/bin/python \
        agent-output/contoso-service-hub-run-2/03-des-diagram.py

Output:
    agent-output/contoso-service-hub-run-2/03-des-diagram.png
"""

from pathlib import Path

from diagrams import Cluster, Diagram, Edge
from diagrams.azure.compute import AKS, Disks, VM
from diagrams.azure.database import CacheForRedis, DatabaseForPostgresqlServers
from diagrams.azure.identity import ExternalIdentities, ManagedIdentities
from diagrams.azure.integration import APIManagement
from diagrams.azure.monitor import ApplicationInsights, LogAnalyticsWorkspaces, Monitor
from diagrams.azure.network import Firewall, FrontDoors, PrivateEndpoint, Subnets, VirtualNetworks
from diagrams.azure.security import KeyVaults
from diagrams.azure.storage import AzureFileshares, BlobStorage
from diagrams.onprem.client import Users
from diagrams.onprem.vcs import Github


OUTPUT_DIR = Path(__file__).resolve().parent
OUTPUT_FILE = OUTPUT_DIR / "03-des-diagram"

GRAPH_ATTR = {
    "bgcolor": "white",
    "pad": "0.8",
    "nodesep": "0.95",
    "ranksep": "1.0",
    "splines": "spline",
    "fontname": "Arial Bold",
    "fontsize": "16",
    "dpi": "160",
    "label": (
        "Contoso Service Hub — Design Topology\n"
        "swedencentral | single-region | zone-redundant | Dev, Staging, Production"
    ),
    "labelloc": "t",
    "labeljust": "c",
}

NODE_ATTR = {
    "fontname": "Arial Bold",
    "fontsize": "11",
    "labelloc": "t",
}

EDGE_ATTR = {
    "fontname": "Arial",
    "fontsize": "9",
}

CLUSTER_STYLE = {
    "margin": "30",
    "fontname": "Arial Bold",
    "fontsize": "14",
}

EDGE_USER = {"style": "bold", "color": "#0078D4", "penwidth": "2.0"}
EDGE_APP = {"style": "solid", "color": "#333333", "penwidth": "1.4"}
EDGE_PRIVATE = {"style": "solid", "color": "#107C10", "penwidth": "1.4"}
EDGE_SECRET = {"style": "dashed", "color": "#C00000", "penwidth": "1.5"}
EDGE_TELEMETRY = {"style": "dotted", "color": "#8764B8", "penwidth": "1.5"}
EDGE_DEVOPS = {"style": "dashed", "color": "#FF8C00", "penwidth": "1.5"}


def main() -> None:
    with Diagram(
        "",
        show=False,
        filename=str(OUTPUT_FILE),
        outformat="png",
        direction="LR",
        graph_attr=GRAPH_ATTR,
        node_attr=NODE_ATTR,
        edge_attr=EDGE_ATTR,
    ):
        n_user_channels = Users("Residents\nVisitors\nPartners\nStaff")

        with Cluster(
            "Global Edge & Identity\nshared across Dev, Staging, Production",
            graph_attr={**CLUSTER_STYLE, "bgcolor": "#F8F9FA", "style": "rounded"},
        ):
            n_id_external = ExternalIdentities("Entra External ID\nCIAM | 15K MAU")
            n_edge_front_door = FrontDoors("Front Door Premium\nWAF + CDN")
            n_edge_policy = Firewall("WAF Policy\nTLS 1.2 + bot rules")
            n_devops_github = Github("GitHub Actions\nDev -> Staging -> Prod")

        with Cluster(
            "Observability & Operations",
            graph_attr={**CLUSTER_STYLE, "bgcolor": "#F3E8FD", "style": "rounded"},
        ):
            n_ops_monitor = Monitor("Azure Monitor\nalerts + dashboards")
            n_ops_app_insights = ApplicationInsights("Application Insights\ndistributed tracing")
            n_ops_log_analytics = LogAnalyticsWorkspaces("Log Analytics\nworkspace-based logs")

        with Cluster(
            "Production Environment\nfull topology shown; lower environments mirror with reduced SKUs",
            graph_attr={**CLUSTER_STYLE, "bgcolor": "#F0F8FF", "style": "rounded"},
        ):
            with Cluster(
                "VNet 10.40.0.0/16\nprivate application and data plane",
                graph_attr={**CLUSTER_STYLE, "bgcolor": "#E0F2F1", "style": "rounded"},
            ):
                n_net_vnet = VirtualNetworks("Service Hub VNet\nPrivate Endpoints")

                with Cluster(
                    "Ingress Subnet 10.40.1.0/24",
                    graph_attr={**CLUSTER_STYLE, "bgcolor": "#E6F4EA", "style": "rounded"},
                ):
                    n_net_ingress = Subnets("Ingress subnet\nprivate API ingress")
                    n_api_apim = APIManagement("API Management\nStandard v2")

                with Cluster(
                    "Application Subnet 10.40.2.0/24",
                    graph_attr={**CLUSTER_STYLE, "bgcolor": "#E8F0FE", "style": "rounded"},
                ):
                    n_app_aks = AKS("AKS Standard\nzone-redundant microservices")
                    n_app_identity = ManagedIdentities("Managed Identity\nworkload + node")
                    n_app_vm = VM("VMs\nnon-container workloads")
                    n_app_disks = Disks("Managed Disks\nPremium SSD")

                with Cluster(
                    "Private Endpoint Subnet 10.40.3.0/24",
                    graph_attr={**CLUSTER_STYLE, "bgcolor": "#FFF9C4", "style": "rounded"},
                ):
                    n_pe_postgres = PrivateEndpoint("PE: PostgreSQL")
                    n_pe_redis = PrivateEndpoint("PE: Managed Redis")
                    n_pe_blob = PrivateEndpoint("PE: Blob Storage")
                    n_pe_files = PrivateEndpoint("PE: Azure Files")
                    n_pe_key_vault = PrivateEndpoint("PE: Key Vault")

            with Cluster(
                "Managed Data Services\npublic network access disabled",
                graph_attr={**CLUSTER_STYLE, "bgcolor": "#FCE4EC", "style": "rounded,dashed"},
            ):
                n_data_postgres = DatabaseForPostgresqlServers(
                    "PostgreSQL Flexible Server\nGP | 256 GB | zone-redundant HA"
                )
                n_data_redis = CacheForRedis("Azure Managed Redis\nM200 memory optimized")
                n_data_blob = BlobStorage("Blob Storage\nobject data")
                n_data_files = AzureFileshares("Azure Files Premium\nshared files")
                n_sec_key_vault = KeyVaults("Key Vault\nRBAC + purge protection")

        n_user_channels >> Edge(label="HTTPS", **EDGE_USER) >> n_edge_front_door
        n_edge_front_door >> Edge(label="WAF inspection", **EDGE_USER) >> n_edge_policy
        n_edge_policy >> Edge(label="private origin", **EDGE_USER) >> n_api_apim

        n_user_channels >> Edge(label="OIDC / OAuth", **EDGE_USER) >> n_id_external
        n_id_external >> Edge(label="JWT / claims", **EDGE_USER) >> n_api_apim

        n_net_vnet >> Edge(label="contains", **EDGE_APP) >> n_net_ingress
        n_net_vnet >> Edge(label="hosts", **EDGE_APP) >> [n_app_aks, n_app_vm]
        n_net_vnet >> Edge(label="terminates", **EDGE_APP) >> [
            n_pe_postgres,
            n_pe_redis,
            n_pe_blob,
            n_pe_files,
            n_pe_key_vault,
        ]

        n_api_apim >> Edge(label="private API", **EDGE_APP) >> n_app_aks
        n_app_aks >> Edge(label="workload identity", **EDGE_SECRET) >> n_app_identity
        n_app_aks >> Edge(label="CSI / PV", **EDGE_APP) >> n_app_disks
        n_app_vm >> Edge(label="attached storage", **EDGE_APP) >> n_app_disks

        n_app_aks >> Edge(label="SQL", **EDGE_PRIVATE) >> n_pe_postgres
        n_app_aks >> Edge(label="cache", **EDGE_PRIVATE) >> n_pe_redis
        n_app_aks >> Edge(label="objects", **EDGE_PRIVATE) >> n_pe_blob
        n_app_aks >> Edge(label="shared files", **EDGE_PRIVATE) >> n_pe_files
        n_app_aks >> Edge(label="secrets", **EDGE_SECRET) >> n_pe_key_vault

        n_app_vm >> Edge(label="maintenance", **EDGE_PRIVATE) >> n_pe_files
        n_app_identity >> Edge(label="RBAC", **EDGE_SECRET) >> n_sec_key_vault

        n_pe_postgres >> Edge(label="TLS 1.2", **EDGE_PRIVATE) >> n_data_postgres
        n_pe_redis >> Edge(label="private access", **EDGE_PRIVATE) >> n_data_redis
        n_pe_blob >> Edge(label="private access", **EDGE_PRIVATE) >> n_data_blob
        n_pe_files >> Edge(label="private access", **EDGE_PRIVATE) >> n_data_files
        n_pe_key_vault >> Edge(label="private access", **EDGE_PRIVATE) >> n_sec_key_vault

        n_devops_github >> Edge(label="CI/CD", **EDGE_DEVOPS) >> n_api_apim
        n_devops_github >> Edge(label="deploy", **EDGE_DEVOPS) >> n_app_aks
        n_devops_github >> Edge(label="ops scripts", **EDGE_DEVOPS) >> n_app_vm

        [n_api_apim, n_app_aks, n_app_vm] >> Edge(label="telemetry", **EDGE_TELEMETRY) >> n_ops_app_insights
        [n_data_postgres, n_data_redis, n_data_blob, n_data_files, n_sec_key_vault] >> Edge(
            label="diagnostics", **EDGE_TELEMETRY
        ) >> n_ops_monitor
        n_ops_app_insights >> Edge(label="workspace", **EDGE_TELEMETRY) >> n_ops_log_analytics
        n_ops_monitor >> Edge(label="logs + alerts", **EDGE_TELEMETRY) >> n_ops_log_analytics

    print(f"Diagram saved to: {OUTPUT_FILE}.png")


if __name__ == "__main__":
    main()
