// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/azure-storage/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "blob storage",
  "How do I blob storage?",
  "Blob storage now",
  "blob storage for my project",
  "file shares",
  "How do I file shares?",
  "File shares now",
  "file shares for my project",
  "queue storage",
  "How do I queue storage?",
  "Queue storage now",
  "queue storage for my project",
  "table storage",
  "How do I table storage?",
  "Table storage now",
  "table storage for my project",
  "data lake",
  "How do I data lake?",
  "Data lake now",
  "data lake for my project",
  "access tiers",
  "How do I access tiers?",
  "Access tiers now",
  "access tiers for my project",
  "lifecycle management",
  "How do I lifecycle management?",
  "Lifecycle management now",
  "lifecycle management for my project",
  "upload files",
  "How do I upload files?",
  "Upload files now",
  "upload files for my project",
  "download blobs",
  "How do I download blobs?",
  "Download blobs now",
  "download blobs for my project",
  "storage accounts",
  "How do I storage accounts?",
  "Storage accounts now",
  "storage accounts for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "SQL databases",
  "How do I SQL databases?",
  "Cosmos DB",
  "How do I cosmos DB?",
  "messaging with Event Hubs or Service Bus",
  "How do I messaging with Event Hubs or Service Bus?",
  "use azure-prepare",
  "run azure-prepare",
  "What is the weather today?",
  "Help me write a poem",
];
