// ============================================================================
// Agent Testing Infrastructure - Main Orchestration Template
// ============================================================================
// Purpose: Ephemeral infrastructure for testing agentic workflows
// Generated by: bicep-code agent
// Template: Azure Verified Modules (AVM) based deployment
// ============================================================================

// =============================================================================
// PARAMETERS
// =============================================================================

@description('Azure region for resource deployment')
@allowed([
  'swedencentral'
  'germanywestcentral'
  'westeurope'
  'northeurope'
])
param location string = 'swedencentral'

@description('Environment name (dev, staging, prod)')
@allowed([
  'dev'
  'staging'
  'prod'
])
param environment string = 'dev'

@description('Project name for resource naming')
@minLength(3)
@maxLength(15)
param projectName string = 'agenttest'

@description('Owner of the resources (for tagging)')
param owner string = 'platform-team'

@description('Cost center for billing allocation')
param costCenter string = 'CC-AGENTOPS'

@description('Deployment timestamp for tagging')
param deploymentDate string = utcNow('yyyy-MM-dd')

@description('SQL Administrator Azure AD Group Object ID')
param sqlAdminGroupObjectId string

@description('SQL Administrator Azure AD Group Name')
param sqlAdminGroupName string = 'SQL Administrators'

// =============================================================================
// VARIABLES
// =============================================================================

// Unique suffix for resource naming (6 characters from resource group ID)
var uniqueSuffix = uniqueString(resourceGroup().id)

// Region abbreviations for CAF naming
var regionAbbreviations = {
  swedencentral: 'swc'
  germanywestcentral: 'gwc'
  westeurope: 'weu'
  northeurope: 'neu'
}
var locationAbbr = regionAbbreviations[location]

// Required tags for all resources (Azure Policy compliant)
var tags = {
  Environment: environment
  ManagedBy: 'Bicep'
  Project: projectName
  Owner: owner
  CostCenter: costCenter
  DeploymentDate: deploymentDate
}

// Static Web App location (region-limited to westeurope for EU)
var staticWebAppLocation = 'westeurope'

// =============================================================================
// MODULES
// =============================================================================

// -----------------------------------------------------------------------------
// Phase 1: Foundation - Monitoring
// -----------------------------------------------------------------------------

module monitoring 'modules/monitoring.bicep' = {
  name: 'monitoring-deployment'
  params: {
    location: location
    locationAbbr: locationAbbr
    environment: environment
    projectName: projectName
    uniqueSuffix: uniqueSuffix
    tags: tags
  }
}

// -----------------------------------------------------------------------------
// Phase 2: Security
// -----------------------------------------------------------------------------

module security 'modules/security.bicep' = {
  name: 'security-deployment'
  params: {
    location: location
    environment: environment
    projectName: projectName
    uniqueSuffix: uniqueSuffix
    tags: tags
    logAnalyticsWorkspaceId: monitoring.outputs.logAnalyticsWorkspaceId
  }
}

// -----------------------------------------------------------------------------
// Phase 2: Storage
// -----------------------------------------------------------------------------

module storage 'modules/storage.bicep' = {
  name: 'storage-deployment'
  params: {
    location: location
    environment: environment
    projectName: projectName
    uniqueSuffix: uniqueSuffix
    tags: tags
    logAnalyticsWorkspaceId: monitoring.outputs.logAnalyticsWorkspaceId
  }
}

// -----------------------------------------------------------------------------
// Phase 3: Compute - App Service
// -----------------------------------------------------------------------------

module computeAppService 'modules/compute-appservice.bicep' = {
  name: 'compute-appservice-deployment'
  params: {
    location: location
    locationAbbr: locationAbbr
    environment: environment
    projectName: projectName
    uniqueSuffix: uniqueSuffix
    tags: tags
    logAnalyticsWorkspaceId: monitoring.outputs.logAnalyticsWorkspaceId
    applicationInsightsConnectionString: monitoring.outputs.applicationInsightsConnectionString
  }
}

// -----------------------------------------------------------------------------
// Phase 3: Compute - Container Apps
// -----------------------------------------------------------------------------

module computeContainer 'modules/compute-container.bicep' = {
  name: 'compute-container-deployment'
  params: {
    location: location
    locationAbbr: locationAbbr
    environment: environment
    projectName: projectName
    uniqueSuffix: uniqueSuffix
    tags: tags
    applicationInsightsConnectionString: monitoring.outputs.applicationInsightsConnectionString
  }
}

// -----------------------------------------------------------------------------
// Phase 3: Data - SQL Server
// -----------------------------------------------------------------------------

module data 'modules/data.bicep' = {
  name: 'data-deployment'
  params: {
    location: location
    locationAbbr: locationAbbr
    environment: environment
    projectName: projectName
    uniqueSuffix: uniqueSuffix
    tags: tags
    sqlAdminGroupObjectId: sqlAdminGroupObjectId
    sqlAdminGroupName: sqlAdminGroupName
  }
}

// -----------------------------------------------------------------------------
// Phase 3: Messaging - Service Bus
// -----------------------------------------------------------------------------

module messaging 'modules/messaging.bicep' = {
  name: 'messaging-deployment'
  params: {
    location: location
    locationAbbr: locationAbbr
    environment: environment
    projectName: projectName
    uniqueSuffix: uniqueSuffix
    tags: tags
    logAnalyticsWorkspaceId: monitoring.outputs.logAnalyticsWorkspaceId
  }
}

// -----------------------------------------------------------------------------
// Phase 4: Web - Static Web App
// -----------------------------------------------------------------------------

module web 'modules/web.bicep' = {
  name: 'web-deployment'
  params: {
    location: staticWebAppLocation // Hardcoded: westeurope (region-limited)
    locationAbbr: 'weu' // Matches staticWebAppLocation
    environment: environment
    projectName: projectName
    uniqueSuffix: uniqueSuffix
    tags: tags
  }
}

// =============================================================================
// OUTPUTS
// =============================================================================

// Monitoring outputs
@description('Log Analytics Workspace ID')
output logAnalyticsWorkspaceId string = monitoring.outputs.logAnalyticsWorkspaceId

@description('Log Analytics Workspace Name')
output logAnalyticsWorkspaceName string = monitoring.outputs.logAnalyticsWorkspaceName

@description('Application Insights ID')
output applicationInsightsId string = monitoring.outputs.applicationInsightsId

@description('Application Insights Name')
output applicationInsightsName string = monitoring.outputs.applicationInsightsName

// Security outputs
@description('Key Vault ID')
output keyVaultId string = security.outputs.keyVaultId

@description('Key Vault Name')
output keyVaultName string = security.outputs.keyVaultName

@description('Key Vault URI')
output keyVaultUri string = security.outputs.keyVaultUri

// Storage outputs
@description('Storage Account ID')
output storageAccountId string = storage.outputs.storageAccountId

@description('Storage Account Name')
output storageAccountName string = storage.outputs.storageAccountName

// Compute App Service outputs
@description('App Service Plan ID')
output appServicePlanId string = computeAppService.outputs.appServicePlanId

@description('App Service ID')
output appServiceId string = computeAppService.outputs.appServiceId

@description('App Service Default Hostname')
output appServiceHostname string = computeAppService.outputs.appServiceHostname

// Compute Container Apps outputs
@description('Container Apps Environment ID')
output containerAppsEnvironmentId string = computeContainer.outputs.containerAppsEnvironmentId

@description('Container App ID')
output containerAppId string = computeContainer.outputs.containerAppId

@description('Container App FQDN')
output containerAppFqdn string = computeContainer.outputs.containerAppFqdn

// Data outputs
@description('SQL Server ID')
output sqlServerId string = data.outputs.sqlServerId

@description('SQL Server FQDN')
output sqlServerFqdn string = data.outputs.sqlServerFqdn

@description('SQL Database ID')
output sqlDatabaseId string = data.outputs.sqlDatabaseId

// Messaging outputs
@description('Service Bus Namespace ID')
output serviceBusNamespaceId string = messaging.outputs.serviceBusNamespaceId

@description('Service Bus Namespace Name')
output serviceBusNamespaceName string = messaging.outputs.serviceBusNamespaceName

// Web outputs
@description('Static Web App ID')
output staticWebAppId string = web.outputs.staticWebAppId

@description('Static Web App Default Hostname')
output staticWebAppHostname string = web.outputs.staticWebAppHostname
