// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/workflow-engine/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "orchestrator step routing",
  "How do I orchestrator step routing?",
  "Orchestrator step routing now",
  "orchestrator step routing for my project",
  "resume from graph",
  "How do I resume from graph?",
  "Resume from graph now",
  "resume from graph for my project",
  "workflow validation",
  "How do I workflow validation?",
  "Workflow validation now",
  "workflow validation for my project",
  "workflow DAG",
  "How do I workflow DAG?",
  "Workflow DAG now",
  "workflow DAG for my project",
  "workflow gate",
  "How do I workflow gate?",
  "Workflow gate now",
  "workflow gate for my project",
  "fan-out pattern",
  "How do I fan-out pattern?",
  "Fan-out pattern now",
  "fan-out pattern for my project",
  "resume-from-graph",
  "How do I resume-from-graph?",
  "Resume-from-graph now",
  "resume-from-graph for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "Azure infrastructure",
  "How do I azure infrastructure?",
  "code generation",
  "How do I code generation?",
  "troubleshooting",
  "How do I troubleshooting?",
  "What is the weather today?",
  "Help me write a poem",
];
