// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/azure-kusto/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "KQL queries",
  "How do I KQL queries?",
  "KQL queries now",
  "KQL queries for my project",
  "Kusto database queries",
  "How do I kusto database queries?",
  "Kusto database queries now",
  "Kusto database queries for my project",
  "Azure Data Explorer",
  "How do I azure Data Explorer?",
  "Azure Data Explorer now",
  "Azure Data Explorer for my project",
  "ADX clusters",
  "How do I ADX clusters?",
  "ADX clusters now",
  "ADX clusters for my project",
  "time series data",
  "How do I time series data?",
  "Time series data now",
  "time series data for my project",
  "IoT telemetry",
  "How do I ioT telemetry?",
  "IoT telemetry now",
  "IoT telemetry for my project",
  "anomaly detection",
  "How do I anomaly detection?",
  "Anomaly detection now",
  "anomaly detection for my project",
  "KQL authoring",
  "How do I KQL authoring?",
  "KQL authoring now",
  "KQL authoring for my project",
  "ADX cluster queries",
  "How do I ADX cluster queries?",
  "ADX cluster queries now",
  "ADX cluster queries for my project",
  "telemetry analysis",
  "How do I telemetry analysis?",
  "Telemetry analysis now",
  "telemetry analysis for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "Application Insights/Log Analytics troubleshooting",
  "How do I application Insights/Log Analytics troubleshooting?",
  "cost analysis",
  "How do I cost analysis?",
  "use azure-diagnostics",
  "run azure-diagnostics",
  "use azure-cost-optimization",
  "run azure-cost-optimization",
  "What is the weather today?",
  "Help me write a poem",
];
