// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/azure-adr/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "create ADR",
  "How do I create ADR?",
  "Create ADR now",
  "create ADR for my project",
  "document decision",
  "How do I document decision?",
  "Document decision now",
  "document decision for my project",
  "architecture decision record",
  "How do I architecture decision record?",
  "Architecture decision record now",
  "architecture decision record for my project",
  "record why we chose",
  "How do I record why we chose?",
  "Record why we chose now",
  "record why we chose for my project",
  "WAF pillar justification",
  "How do I WAF pillar justification?",
  "WAF pillar justification now",
  "WAF pillar justification for my project",
  "trade-off analysis",
  "How do I trade-off analysis?",
  "Trade-off analysis now",
  "trade-off analysis for my project",
  "ADR scaffolding",
  "How do I ADR scaffolding?",
  "ADR scaffolding now",
  "ADR scaffolding for my project",
  "design ADRs",
  "How do I design ADRs?",
  "Design ADRs now",
  "design ADRs for my project",
  "as-built ADRs",
  "How do I as-built ADRs?",
  "As-built ADRs now",
  "as-built ADRs for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "Bicep/Terraform code",
  "How do I bicep/Terraform code?",
  "architecture diagrams",
  "How do I architecture diagrams?",
  "cost estimates",
  "How do I cost estimates?",
  "use drawio",
  "run drawio",
  "use cost-estimate-subagent",
  "run cost-estimate-subagent",
  "What is the weather today?",
  "Help me write a poem",
];
