// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/azure-defaults/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "Azure naming convention",
  "How do I azure naming convention?",
  "Azure naming convention now",
  "Azure naming convention for my project",
  "CAF naming",
  "How do I CAF naming?",
  "CAF naming now",
  "CAF naming for my project",
  "resource tags",
  "How do I resource tags?",
  "Resource tags now",
  "resource tags for my project",
  "AVM module",
  "How do I AVM module?",
  "AVM module now",
  "AVM module for my project",
  "security baseline",
  "How do I security baseline?",
  "Security baseline now",
  "security baseline for my project",
  "region default",
  "How do I region default?",
  "Region default now",
  "region default for my project",
  "any agent generating or planning Azure resources",
  "How do I any agent generating or planning Azure resources?",
  "Any agent generating or planning Azure resources now",
  "any agent generating or planning Azure resources for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "artifact template structures",
  "How do I artifact template structures?",
  "pricing lookups",
  "How do I pricing lookups?",
  "use azure-artifacts",
  "run azure-artifacts",
  "What is the weather today?",
  "Help me write a poem",
];
