// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/azure-compute/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "recommend VM size",
  "How do I recommend VM size?",
  "Recommend VM size now",
  "recommend VM size for my project",
  "choose Azure VM",
  "How do I choose Azure VM?",
  "Choose Azure VM now",
  "choose Azure VM for my project",
  "GPU VM",
  "How do I GPU VM?",
  "GPU VM now",
  "GPU VM for my project",
  "compare VM sizes",
  "How do I compare VM sizes?",
  "Compare VM sizes now",
  "compare VM sizes for my project",
  "VMSS vs VM",
  "How do I VMSS vs VM?",
  "VMSS vs VM now",
  "VMSS vs VM for my project",
  "autoscale VMs",
  "How do I autoscale VMs?",
  "Autoscale VMs now",
  "autoscale VMs for my project",
  "VM family selection",
  "How do I VM family selection?",
  "VM family selection now",
  "VM family selection for my project",
  "VMSS sizing",
  "How do I VMSS sizing?",
  "VMSS sizing now",
  "VMSS sizing for my project",
  "confidential computing recommendations",
  "How do I confidential computing recommendations?",
  "Confidential computing recommendations now",
  "confidential computing recommendations for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "provisioning VMs",
  "How do I provisioning VMs?",
  "VM pricing for budgets",
  "How do I VM pricing for budgets?",
  "use azure-prepare",
  "run azure-prepare",
  "use azure-pricing",
  "run azure-pricing",
  "What is the weather today?",
  "Help me write a poem",
];
