// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/docs-writer/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "update docs",
  "How do I update docs?",
  "Update docs now",
  "update docs for my project",
  "doc gardening",
  "How do I doc gardening?",
  "Doc gardening now",
  "doc gardening for my project",
  "staleness check",
  "How do I staleness check?",
  "Staleness check now",
  "staleness check for my project",
  "changelog entry",
  "How do I changelog entry?",
  "Changelog entry now",
  "changelog entry for my project",
  "repo explanation",
  "How do I repo explanation?",
  "Repo explanation now",
  "repo explanation for my project",
  "agent change docs",
  "How do I agent change docs?",
  "Agent change docs now",
  "agent change docs for my project",
  "skill change docs",
  "How do I skill change docs?",
  "Skill change docs now",
  "skill change docs for my project",
  "post-merge doc updates",
  "How do I post-merge doc updates?",
  "Post-merge doc updates now",
  "post-merge doc updates for my project",
  "agent/skill freshness audits",
  "How do I agent/skill freshness audits?",
  "Agent/skill freshness audits now",
  "agent/skill freshness audits for my project",
  "changelog drafting",
  "How do I changelog drafting?",
  "Changelog drafting now",
  "changelog drafting for my project",
  "README/CONTRIBUTING gardening",
  "How do I README/CONTRIBUTING gardening?",
  "README/CONTRIBUTING gardening now",
  "README/CONTRIBUTING gardening for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "agent definitions themselves",
  "How do I agent definitions themselves?",
  "skill SKILL.md content",
  "How do I skill SKILL.md content?",
  "site theme/build",
  "How do I site theme/build?",
  "What is the weather today?",
  "Help me write a poem",
];
