// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/azure-diagnostics/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "debug production issues",
  "How do I debug production issues?",
  "Debug production issues now",
  "debug production issues for my project",
  "troubleshoot container apps",
  "How do I troubleshoot container apps?",
  "Troubleshoot container apps now",
  "troubleshoot container apps for my project",
  "troubleshoot function apps",
  "How do I troubleshoot function apps?",
  "Troubleshoot function apps now",
  "troubleshoot function apps for my project",
  "image pull failures",
  "How do I image pull failures?",
  "Image pull failures now",
  "image pull failures for my project",
  "cold start issues",
  "How do I cold start issues?",
  "Cold start issues now",
  "cold start issues for my project",
  "health probe failures",
  "How do I health probe failures?",
  "Health probe failures now",
  "health probe failures for my project",
  "post-deployment troubleshooting",
  "How do I post-deployment troubleshooting?",
  "Post-deployment troubleshooting now",
  "post-deployment troubleshooting for my project",
  "root-cause analysis",
  "How do I root-cause analysis?",
  "Root-cause analysis now",
  "root-cause analysis for my project",
  "log triage",
  "How do I log triage?",
  "Log triage now",
  "log triage for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "pre-deployment validation",
  "How do I pre-deployment validation?",
  "cost analysis",
  "How do I cost analysis?",
  "use azure-validate",
  "run azure-validate",
  "use azure-cost-optimization",
  "run azure-cost-optimization",
  "What is the weather today?",
  "Help me write a poem",
];
