// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/azure-artifacts/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "generate artifact",
  "How do I generate artifact?",
  "Generate artifact now",
  "generate artifact for my project",
  "check H2 structure",
  "How do I check H2 structure?",
  "Check H2 structure now",
  "check H2 structure for my project",
  "artifact template",
  "How do I artifact template?",
  "Artifact template now",
  "artifact template for my project",
  "step 7 as-built",
  "How do I step 7 as-built?",
  "Step 7 as-built now",
  "step 7 as-built for my project",
  "generating any agent artifact",
  "How do I generating any agent artifact?",
  "Generating any agent artifact now",
  "generating any agent artifact for my project",
  "checking H2 structure compliance",
  "How do I checking H2 structure compliance?",
  "Checking H2 structure compliance now",
  "checking H2 structure compliance for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "Azure resource configuration",
  "How do I azure resource configuration?",
  "Bicep/Terraform patterns",
  "How do I bicep/Terraform patterns?",
  "use azure-defaults",
  "run azure-defaults",
  "use azure-bicep-patterns",
  "run azure-bicep-patterns",
  "What is the weather today?",
  "Help me write a poem",
];
