// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/azure-deploy/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "run azd up",
  "How do I run azd up?",
  "Run azd up now",
  "run azd up for my project",
  "run azd deploy",
  "How do I run azd deploy?",
  "Run azd deploy now",
  "run azd deploy for my project",
  "push to production",
  "How do I push to production?",
  "Push to production now",
  "push to production for my project",
  "go live",
  "How do I go live?",
  "Go live now",
  "go live for my project",
  "bicep deploy",
  "How do I bicep deploy?",
  "Bicep deploy now",
  "bicep deploy for my project",
  "terraform apply",
  "How do I terraform apply?",
  "Terraform apply now",
  "terraform apply for my project",
  "publish to Azure",
  "How do I publish to Azure?",
  "Publish to Azure now",
  "publish to Azure for my project",
  "deploying validated infra; lifting existing IaC to cloud",
  "How do I deploying validated infra; lifting existing IaC to cloud?",
  "Deploying validated infra; lifting existing IaC to cloud now",
  "deploying validated infra; lifting existing IaC to cloud for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "creating new apps",
  "How do I creating new apps?",
  "generating IaC",
  "How do I generating IaC?",
  "pre-deployment checks",
  "How do I pre-deployment checks?",
  "use azure-prepare",
  "run azure-prepare",
  "use azure-validate",
  "run azure-validate",
  "What is the weather today?",
  "Help me write a poem",
];
