// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/azure-cost-optimization/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "optimize Azure costs",
  "How do I optimize Azure costs?",
  "Optimize Azure costs now",
  "optimize Azure costs for my project",
  "reduce Azure spending",
  "How do I reduce Azure spending?",
  "Reduce Azure spending now",
  "reduce Azure spending for my project",
  "find cost savings",
  "How do I find cost savings?",
  "Find cost savings now",
  "find cost savings for my project",
  "rightsize VMs",
  "How do I rightsize VMs?",
  "Rightsize VMs now",
  "rightsize VMs for my project",
  "find orphaned resources",
  "How do I find orphaned resources?",
  "Find orphaned resources now",
  "find orphaned resources for my project",
  "optimize Redis costs",
  "How do I optimize Redis costs?",
  "Optimize Redis costs now",
  "optimize Redis costs for my project",
  "cost reduction reports",
  "How do I cost reduction reports?",
  "Cost reduction reports now",
  "cost reduction reports for my project",
  "orphaned-resource discovery",
  "How do I orphaned-resource discovery?",
  "Orphaned-resource discovery now",
  "orphaned-resource discovery for my project",
  "rightsizing recommendations",
  "How do I rightsizing recommendations?",
  "Rightsizing recommendations now",
  "rightsizing recommendations for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "deploying resources",
  "How do I deploying resources?",
  "general diagnostics",
  "How do I general diagnostics?",
  "security issues",
  "How do I security issues?",
  "use azure-deploy",
  "run azure-deploy",
  "use azure-diagnostics",
  "run azure-diagnostics",
  "use azure-compliance",
  "run azure-compliance",
  "What is the weather today?",
  "Help me write a poem",
];
