"""Step 3 design architecture diagram for my-demo (non-Mermaid, deterministic layout).

Generated by design agent | 2026-02-24
"""

from diagrams import Cluster, Diagram, Edge
from diagrams.azure.compute import FunctionApps
from diagrams.azure.monitor import ApplicationInsights
from diagrams.azure.web import StaticApps
from diagrams.onprem.client import User
from diagrams.onprem.vcs import Github

graph_attr = {
    "bgcolor": "white",
    "pad": "0.6",
    "nodesep": "1.0",
    "ranksep": "1.2",
    "splines": "polyline",
    "fontsize": "14",
    "labelloc": "t",
    "label": "Step 3 Design Architecture | my-demo | westeurope",
}

cluster_attr = {
    "style": "rounded",
    "fontsize": "12",
}

with Diagram(
    "my-demo-design",
    filename="agent-output/my-demo/03-des-diagram",
    show=False,
    direction="LR",
    outformat="png",
    graph_attr=graph_attr,
):
    with Cluster("clu_ext_public", graph_attr=cluster_attr):
        n_edge_user_viewer = User("demo viewer")
        n_int_github_repo = Github("github repo")

    with Cluster("clu_sub_azure_westeurope", graph_attr=cluster_attr):
        with Cluster("clu_rg_my_demo_dev", graph_attr=cluster_attr):
            with Cluster("clu_tier_web", graph_attr=cluster_attr):
                n_web_staticapps_frontend = StaticApps("static web app")

            with Cluster("clu_tier_app", graph_attr=cluster_attr):
                n_app_functionapps_api = FunctionApps("functions api")

            with Cluster("clu_tier_ops", graph_attr=cluster_attr):
                n_ops_applicationinsights_main = ApplicationInsights("app insights")

    e_runtime = Edge(color="#1565C0", style="bold")
    e_control = Edge(color="#455A64", style="dashed")
    e_observe = Edge(color="#6A1B9A", style="dotted")

    _flow_01 = n_edge_user_viewer >> Edge(label="request", **e_runtime.attrs) >> n_web_staticapps_frontend
    _flow_02 = n_web_staticapps_frontend >> Edge(label="request", **e_runtime.attrs) >> n_app_functionapps_api
    _flow_03 = n_app_functionapps_api >> Edge(label="response", **e_runtime.attrs) >> n_web_staticapps_frontend

    _flow_04 = n_int_github_repo >> Edge(label="admin", **e_control.attrs) >> n_web_staticapps_frontend

    _flow_05 = n_app_functionapps_api >> Edge(label="auth", **e_control.attrs) >> n_ops_applicationinsights_main
    _flow_06 = n_web_staticapps_frontend >> Edge(label="telemetry", **e_observe.attrs) >> n_ops_applicationinsights_main
    _flow_07 = n_app_functionapps_api >> Edge(label="telemetry", **e_observe.attrs) >> n_ops_applicationinsights_main

print("Generated diagram: agent-output/my-demo/03-des-diagram.png")
