// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/drawio/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "draw.io diagram",
  "How do I draw.io diagram?",
  "Draw.io diagram now",
  "draw.io diagram for my project",
  "Azure architecture diagram",
  "How do I azure architecture diagram?",
  "Azure architecture diagram now",
  "Azure architecture diagram for my project",
  "as-built diagram",
  "How do I as-built diagram?",
  "As-built diagram now",
  "as-built diagram for my project",
  "runtime flow diagram",
  "How do I runtime flow diagram?",
  "Runtime flow diagram now",
  "runtime flow diagram for my project",
  "dependency diagram",
  "How do I dependency diagram?",
  "Dependency diagram now",
  "dependency diagram for my project",
  "production Azure architecture visuals",
  "How do I production Azure architecture visuals?",
  "Production Azure architecture visuals now",
  "production Azure architecture visuals for my project",
  "multi-resource layouts",
  "How do I multi-resource layouts?",
  "Multi-resource layouts now",
  "multi-resource layouts for my project",
  "design-stage and as-built artifacts",
  "How do I design-stage and as-built artifacts?",
  "Design-stage and as-built artifacts now",
  "design-stage and as-built artifacts for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "WAF/cost charts",
  "How do I WAF/cost charts?",
  "inline Mermaid",
  "How do I inline Mermaid?",
  "use python-diagrams",
  "run python-diagrams",
  "use mermaid",
  "run mermaid",
  "What is the weather today?",
  "Help me write a poem",
];
