// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/context-management/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "context optimization",
  "How do I context optimization?",
  "Context optimization now",
  "context optimization for my project",
  "token budget management",
  "How do I token budget management?",
  "Token budget management now",
  "token budget management for my project",
  "runtime compression",
  "How do I runtime compression?",
  "Runtime compression now",
  "runtime compression for my project",
  "log parsing",
  "How do I log parsing?",
  "Log parsing now",
  "log parsing for my project",
  "redundancy detection",
  "How do I redundancy detection?",
  "Redundancy detection now",
  "redundancy detection for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "Azure infrastructure",
  "How do I azure infrastructure?",
  "Bicep/Terraform code",
  "How do I bicep/Terraform code?",
  "architecture design",
  "How do I architecture design?",
  "deployments",
  "How do I deployments?",
  "What is the weather today?",
  "Help me write a poem",
];
