// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/azure-governance-discovery/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "Azure policy discovery",
  "How do I azure policy discovery?",
  "Azure policy discovery now",
  "Azure policy discovery for my project",
  "effective policy assignments",
  "How do I effective policy assignments?",
  "Effective policy assignments now",
  "effective policy assignments for my project",
  "governance constraints",
  "How do I governance constraints?",
  "Governance constraints now",
  "governance constraints for my project",
  "04g-Governance Phase 1",
  "How do I 04g-Governance Phase 1?",
  "04g-Governance Phase 1 now",
  "04g-Governance Phase 1 for my project",
  "refresh governance JSON",
  "How do I refresh governance JSON?",
  "Refresh governance JSON now",
  "refresh governance JSON for my project",
  "04g Phase 1 discovery",
  "How do I 04g Phase 1 discovery?",
  "04g Phase 1 discovery now",
  "04g Phase 1 discovery for my project",
  "refreshing `04-governance-constraints.json`",
  "How do I refreshing `04-governance-constraints.json`?",
  "Refreshing `04-governance-constraints.json` now",
  "refreshing `04-governance-constraints.json` for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "artifact writing",
  "How do I artifact writing?",
  "architecture mapping",
  "How do I architecture mapping?",
  "traffic-light rendering",
  "How do I traffic-light rendering?",
  "challenger orchestration",
  "How do I challenger orchestration?",
  "What is the weather today?",
  "Help me write a poem",
];
