// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/azure-bicep-patterns/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "hub-spoke Bicep",
  "How do I hub-spoke Bicep?",
  "Hub-spoke Bicep now",
  "hub-spoke Bicep for my project",
  "private endpoint module",
  "How do I private endpoint module?",
  "Private endpoint module now",
  "private endpoint module for my project",
  "diagnostic settings",
  "How do I diagnostic settings?",
  "Diagnostic settings now",
  "diagnostic settings for my project",
  "AVM Bicep composition",
  "How do I AVM Bicep composition?",
  "AVM Bicep composition now",
  "AVM Bicep composition for my project",
  "Bicep template design",
  "How do I bicep template design?",
  "Bicep template design now",
  "Bicep template design for my project",
  "hub-spoke networking",
  "How do I hub-spoke networking?",
  "Hub-spoke networking now",
  "hub-spoke networking for my project",
  "private endpoint patterns",
  "How do I private endpoint patterns?",
  "Private endpoint patterns now",
  "private endpoint patterns for my project",
  "AVM modules",
  "How do I AVM modules?",
  "AVM modules now",
  "AVM modules for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "Terraform code",
  "How do I terraform code?",
  "architecture decisions",
  "How do I architecture decisions?",
  "troubleshooting",
  "How do I troubleshooting?",
  "diagram generation",
  "How do I diagram generation?",
  "use terraform-patterns",
  "run terraform-patterns",
  "use azure-adr",
  "run azure-adr",
  "use drawio",
  "run drawio",
  "What is the weather today?",
  "Help me write a poem",
];
