// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/golden-principles/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "golden principles",
  "How do I golden principles?",
  "Golden principles now",
  "golden principles for my project",
  "agent behavior rules",
  "How do I agent behavior rules?",
  "Agent behavior rules now",
  "agent behavior rules for my project",
  "operating philosophy",
  "How do I operating philosophy?",
  "Operating philosophy now",
  "operating philosophy for my project",
  "principle lookup",
  "How do I principle lookup?",
  "Principle lookup now",
  "principle lookup for my project",
  "governance invariants",
  "How do I governance invariants?",
  "Governance invariants now",
  "governance invariants for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "Azure infrastructure",
  "How do I azure infrastructure?",
  "code generation",
  "How do I code generation?",
  "troubleshooting",
  "How do I troubleshooting?",
  "diagram creation",
  "How do I diagram creation?",
  "What is the weather today?",
  "Help me write a poem",
];
