// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/microsoft-docs/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "Microsoft Learn",
  "How do I microsoft Learn?",
  "Microsoft Learn now",
  "Microsoft Learn for my project",
  "Azure docs",
  "How do I azure docs?",
  "Azure docs now",
  "Azure docs for my project",
  "quickstart guide",
  "How do I quickstart guide?",
  "Quickstart guide now",
  "quickstart guide for my project",
  "limits and quotas",
  "How do I limits and quotas?",
  "Limits and quotas now",
  "limits and quotas for my project",
  "WAF reference",
  "How do I WAF reference?",
  "WAF reference now",
  "WAF reference for my project",
  "architecture pattern docs",
  "How do I architecture pattern docs?",
  "Architecture pattern docs now",
  "architecture pattern docs for my project",
  "Azure service overviews",
  "How do I azure service overviews?",
  "Azure service overviews now",
  "Azure service overviews for my project",
  "quickstarts",
  "How do I quickstarts?",
  "Quickstarts now",
  "quickstarts for my project",
  "configuration guides",
  "How do I configuration guides?",
  "Configuration guides now",
  "configuration guides for my project",
  "best practices",
  "How do I best practices?",
  "Best practices now",
  "best practices for my project",
  "architecture patterns",
  "How do I architecture patterns?",
  "Architecture patterns now",
  "architecture patterns for my project",
  "WAF pillar references",
  "How do I WAF pillar references?",
  "WAF pillar references now",
  "WAF pillar references for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "Azure pricing",
  "How do I azure pricing?",
  "use azure-pricing",
  "run azure-pricing",
  "What is the weather today?",
  "Help me write a poem",
];
