// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/azure-compliance/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "compliance scan",
  "How do I compliance scan?",
  "Compliance scan now",
  "compliance scan for my project",
  "security audit",
  "How do I security audit?",
  "Security audit now",
  "security audit for my project",
  "Key Vault expiration check",
  "How do I key Vault expiration check?",
  "Key Vault expiration check now",
  "Key Vault expiration check for my project",
  "expired certificates",
  "How do I expired certificates?",
  "Expired certificates now",
  "expired certificates for my project",
  "orphaned resources",
  "How do I orphaned resources?",
  "Orphaned resources now",
  "orphaned resources for my project",
  "pre-azqr compliance assessment",
  "How do I pre-azqr compliance assessment?",
  "Pre-azqr compliance assessment now",
  "pre-azqr compliance assessment for my project",
  "Key Vault audits",
  "How do I key Vault audits?",
  "Key Vault audits now",
  "Key Vault audits for my project",
  "security posture evaluation",
  "How do I security posture evaluation?",
  "Security posture evaluation now",
  "security posture evaluation for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "cost analysis",
  "How do I cost analysis?",
  "governance discovery",
  "How do I governance discovery?",
  "use azure-cost-optimization",
  "run azure-cost-optimization",
  "use azure-governance-discovery",
  "run azure-governance-discovery",
  "What is the weather today?",
  "Help me write a poem",
];
