// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/azure-validate/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "validate my app",
  "How do I validate my app?",
  "Validate my app now",
  "validate my app for my project",
  "check deployment readiness",
  "How do I check deployment readiness?",
  "Check deployment readiness now",
  "check deployment readiness for my project",
  "run preflight checks",
  "How do I run preflight checks?",
  "Run preflight checks now",
  "run preflight checks for my project",
  "validate azure.yaml",
  "How do I validate azure.yaml?",
  "Validate azure.yaml now",
  "validate azure.yaml for my project",
  "validate Bicep",
  "How do I validate Bicep?",
  "Validate Bicep now",
  "validate Bicep for my project",
  "test before deploying",
  "How do I test before deploying?",
  "Test before deploying now",
  "test before deploying for my project",
  "validate Azure Functions",
  "How do I validate Azure Functions?",
  "Validate Azure Functions now",
  "validate Azure Functions for my project",
  "pre-deployment readiness checks",
  "How do I pre-deployment readiness checks?",
  "Pre-deployment readiness checks now",
  "pre-deployment readiness checks for my project",
  "Bicep + Terraform preflight",
  "How do I bicep + Terraform preflight?",
  "Bicep + Terraform preflight now",
  "Bicep + Terraform preflight for my project",
  "Azure Functions validation",
  "How do I azure Functions validation?",
  "Azure Functions validation now",
  "Azure Functions validation for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "post-deployment troubleshooting",
  "How do I post-deployment troubleshooting?",
  "executing deployments",
  "How do I executing deployments?",
  "use azure-diagnostics",
  "run azure-diagnostics",
  "use azure-deploy",
  "run azure-deploy",
  "What is the weather today?",
  "Help me write a poem",
];
