"""Contoso Service Hub design architecture diagram.

Generated by design agent | 2026-03-17

Prerequisites:
    pip install diagrams pillow
    apt-get install -y graphviz

Usage:
    /workspaces/azure-agentic-infraops/.venv/bin/python \
        agent-output/contoso-service-hub-run-3/03-des-diagram.py

Output:
    agent-output/contoso-service-hub-run-3/03-des-diagram.png
"""

from pathlib import Path

from diagrams import Cluster, Diagram, Edge
from diagrams.azure.compute import AKS, VM
from diagrams.azure.database import CacheForRedis, DatabaseForPostgresqlServers
from diagrams.azure.identity import ExternalIdentities, ManagedIdentities
from diagrams.azure.integration import APIManagement
from diagrams.azure.monitor import ApplicationInsights, LogAnalyticsWorkspaces, Monitor
from diagrams.azure.network import Firewall, FrontDoors, PrivateEndpoint, Subnets, VirtualNetworks
from diagrams.azure.security import KeyVaults
from diagrams.azure.storage import BlobStorage
from diagrams.onprem.client import Users
from diagrams.onprem.vcs import Github


OUTPUT_DIR = Path(__file__).resolve().parent
OUTPUT_FILE = OUTPUT_DIR / "03-des-diagram"

GRAPH_ATTR = {
    "bgcolor": "white",
    "pad": "0.8",
    "nodesep": "0.95",
    "ranksep": "1.05",
    "splines": "spline",
    "fontname": "Arial Bold",
    "fontsize": "16",
    "dpi": "170",
    "label": (
        "Contoso Service Hub - Design Topology\n"
        "swedencentral | GDPR-compliant | single-region | private data plane"
    ),
    "labelloc": "t",
    "labeljust": "c",
}

NODE_ATTR = {
    "fontname": "Arial Bold",
    "fontsize": "11",
    "labelloc": "t",
}

EDGE_ATTR = {
    "fontname": "Arial",
    "fontsize": "9",
}

CLUSTER_STYLE = {
    "margin": "30",
    "fontname": "Arial Bold",
    "fontsize": "14",
}

EDGE_USER = {"style": "bold", "color": "#0078D4", "penwidth": "2.0"}
EDGE_APP = {"style": "solid", "color": "#333333", "penwidth": "1.4"}
EDGE_PRIVATE = {"style": "solid", "color": "#107C10", "penwidth": "1.4"}
EDGE_SECRET = {"style": "dashed", "color": "#C00000", "penwidth": "1.5"}
EDGE_TELEMETRY = {"style": "dotted", "color": "#8764B8", "penwidth": "1.6"}
EDGE_DEVOPS = {"style": "dashed", "color": "#FF8C00", "penwidth": "1.5"}


def main() -> None:
    with Diagram(
        "",
        show=False,
        filename=str(OUTPUT_FILE),
        outformat="png",
        direction="LR",
        graph_attr=GRAPH_ATTR,
        node_attr=NODE_ATTR,
        edge_attr=EDGE_ATTR,
    ):
        n_user_channels = Users("Residents\nVisitors\nTenants\nPartners")

        with Cluster(
            "Global Edge and Identity",
            graph_attr={**CLUSTER_STYLE, "bgcolor": "#F8F9FA", "style": "rounded"},
        ):
            n_edge_front_door = FrontDoors("Front Door Premium\nWAF + CDN")
            n_edge_waf = Firewall("WAF policy\nOWASP + bot protection")
            n_id_external = ExternalIdentities("Entra External ID\nCIAM + MFA")

        with Cluster(
            "Observability and DevOps",
            graph_attr={**CLUSTER_STYLE, "bgcolor": "#F4ECFF", "style": "rounded"},
        ):
            n_ops_monitor = Monitor("Azure Monitor\nalerts + metrics")
            n_ops_app_insights = ApplicationInsights("Application Insights\ntraces + dependencies")
            n_ops_log_analytics = LogAnalyticsWorkspaces("Log Analytics\nworkspace")
            n_devops_github = Github("GitHub Actions\nCI/CD")

        with Cluster(
            "Production Environment\nlower environments mirror with reduced SKUs",
            graph_attr={**CLUSTER_STYLE, "bgcolor": "#F0F8FF", "style": "rounded"},
        ):
            with Cluster(
                "VNet 10.40.0.0/16",
                graph_attr={**CLUSTER_STYLE, "bgcolor": "#E8F5E9", "style": "rounded"},
            ):
                n_net_vnet = VirtualNetworks("Service Hub VNet\ninternal-only backend")

                with Cluster(
                    "Ingress subnet 10.40.1.0/24",
                    graph_attr={**CLUSTER_STYLE, "bgcolor": "#E3F2FD", "style": "rounded"},
                ):
                    n_net_ingress = Subnets("APIM internal subnet")
                    n_api_apim = APIManagement("API Management\ninternal VNet mode")

                with Cluster(
                    "Application subnet 10.40.2.0/24",
                    graph_attr={**CLUSTER_STYLE, "bgcolor": "#E8EAF6", "style": "rounded"},
                ):
                    n_app_aks = AKS("AKS Standard\n3 x D8s_v5 nodes")
                    n_app_identity = ManagedIdentities("Managed identity\nworkload + node")
                    n_app_sidecar = Monitor("Monitoring sidecar\nOTel collector")
                    n_app_vm = VM("Ops and batch VMs\nD-series")

                with Cluster(
                    "Private endpoint subnet 10.40.3.0/24",
                    graph_attr={**CLUSTER_STYLE, "bgcolor": "#FFF8E1", "style": "rounded"},
                ):
                    n_pe_postgres = PrivateEndpoint("PE: PostgreSQL")
                    n_pe_redis = PrivateEndpoint("PE: Redis")
                    n_pe_storage = PrivateEndpoint("PE: Storage")
                    n_pe_key_vault = PrivateEndpoint("PE: Key Vault")

            with Cluster(
                "Managed data and security services\npublic network access disabled",
                graph_attr={**CLUSTER_STYLE, "bgcolor": "#FCE4EC", "style": "rounded,dashed"},
            ):
                n_data_postgres = DatabaseForPostgresqlServers(
                    "PostgreSQL Flexible Server\nGP | HA | private access"
                )
                n_data_redis = CacheForRedis("Azure Cache for Redis\nPremium P4 | 53 GB")
                n_data_storage = BlobStorage("Storage Account\nZRS | blob + files")
                n_sec_key_vault = KeyVaults("Key Vault\nRBAC + purge protection")

        n_user_channels >> Edge(label="HTTPS", **EDGE_USER) >> n_edge_front_door
        n_edge_front_door >> Edge(label="WAF inspection", **EDGE_USER) >> n_edge_waf
        n_edge_waf >> Edge(label="private origin", **EDGE_USER) >> n_api_apim

        n_user_channels >> Edge(label="OIDC / OAuth", **EDGE_USER) >> n_id_external
        n_id_external >> Edge(label="tokens", **EDGE_USER) >> n_api_apim

        n_net_vnet >> Edge(label="contains", **EDGE_APP) >> n_net_ingress
        n_net_vnet >> Edge(label="hosts", **EDGE_APP) >> [n_app_aks, n_app_vm]
        n_net_vnet >> Edge(label="terminates", **EDGE_APP) >> [
            n_pe_postgres,
            n_pe_redis,
            n_pe_storage,
            n_pe_key_vault,
        ]

        n_api_apim >> Edge(label="private APIs", **EDGE_APP) >> n_app_aks
        n_app_aks >> Edge(label="identity", **EDGE_SECRET) >> n_app_identity
        n_app_aks >> Edge(label="telemetry", **EDGE_TELEMETRY) >> n_app_sidecar

        n_app_aks >> Edge(label="SQL", **EDGE_PRIVATE) >> n_pe_postgres
        n_app_aks >> Edge(label="cache", **EDGE_PRIVATE) >> n_pe_redis
        n_app_aks >> Edge(label="objects + files", **EDGE_PRIVATE) >> n_pe_storage
        n_app_aks >> Edge(label="secrets", **EDGE_SECRET) >> n_pe_key_vault

        n_app_vm >> Edge(label="admin + jobs", **EDGE_PRIVATE) >> n_api_apim
        n_app_vm >> Edge(label="maintenance", **EDGE_PRIVATE) >> n_pe_storage

        n_pe_postgres >> Edge(label="TLS 1.2", **EDGE_PRIVATE) >> n_data_postgres
        n_pe_redis >> Edge(label="private access", **EDGE_PRIVATE) >> n_data_redis
        n_pe_storage >> Edge(label="private access", **EDGE_PRIVATE) >> n_data_storage
        n_pe_key_vault >> Edge(label="private access", **EDGE_PRIVATE) >> n_sec_key_vault

        n_app_identity >> Edge(label="RBAC", **EDGE_SECRET) >> n_sec_key_vault

        n_app_sidecar >> Edge(label="traces", **EDGE_TELEMETRY) >> n_ops_app_insights
        [n_api_apim, n_app_vm, n_data_postgres, n_data_redis, n_data_storage, n_sec_key_vault] >> Edge(
            label="diagnostics", **EDGE_TELEMETRY
        ) >> n_ops_monitor
        n_ops_app_insights >> Edge(label="workspace", **EDGE_TELEMETRY) >> n_ops_log_analytics
        n_ops_monitor >> Edge(label="logs + alerts", **EDGE_TELEMETRY) >> n_ops_log_analytics

        n_devops_github >> Edge(label="deploy", **EDGE_DEVOPS) >> n_app_aks
        n_devops_github >> Edge(label="publish APIs", **EDGE_DEVOPS) >> n_api_apim
        n_devops_github >> Edge(label="ops scripts", **EDGE_DEVOPS) >> n_app_vm

    print(f"Diagram saved to: {OUTPUT_FILE}.png")


if __name__ == "__main__":
    main()
