"""
04-dependency-diagram.py — Module dependency graph for Contoso Service Hub Bicep implementation.
Generated by bicep-plan agent | 2026-03-17
"""

from diagrams import Diagram, Cluster, Edge
from diagrams.azure.compute import KubernetesServices, VirtualMachinesClassic as VM, ContainerRegistries, Disks
from diagrams.azure.database import DatabaseForPostgresqlServers as DatabaseForPostgreSQL, CacheForRedis
from diagrams.azure.network import VirtualNetworks, FrontDoors, ApplicationGateway
from diagrams.azure.security import KeyVaults
from diagrams.azure.storage import StorageAccounts
from diagrams.azure.analytics import LogAnalyticsWorkspaces
from diagrams.azure.general import CostBudgets
from diagrams.azure.devops import ApplicationInsights

graph_attr = {
    "fontsize": "16",
    "bgcolor": "white",
    "pad": "0.5",
    "rankdir": "TB",
    "dpi": "150",
}

with Diagram(
    "Contoso Service Hub — Bicep Module Dependencies",
    filename="agent-output/contoso-service-hub-run-3/04-dependency-diagram",
    show=False,
    direction="TB",
    graph_attr=graph_attr,
    outformat="png",
):
    # Phase 1: Foundation
    with Cluster("Phase 1: Foundation"):
        law = LogAnalyticsWorkspaces("monitoring.bicep\nLog Analytics + App Insights")
        vnet = VirtualNetworks("networking.bicep\nVNet + Subnets + NSGs")
        kv = KeyVaults("key-vault.bicep\nKey Vault")
        budget = CostBudgets("budget.bicep\nCost Budget + Alerts")

    # Phase 2: Data
    with Cluster("Phase 2: Data"):
        pg = DatabaseForPostgreSQL("postgresql.bicep\nPostgreSQL Flex Server")
        redis = CacheForRedis("redis.bicep\nRedis Premium P4")
        storage = StorageAccounts("storage.bicep\nStorage (ZRS)")
        disk = Disks("managed-disk.bicep\nPremium SSD")
        pe = ApplicationGateway("private-endpoints.bicep\n5 Private Endpoints")

    # Phase 3: Edge
    with Cluster("Phase 3: Edge"):
        apim = ApplicationGateway("apim.bicep\nAPIM Internal VNet")
        fd = FrontDoors("front-door.bicep\nFront Door + WAF")

    # Phase 4: Platform
    with Cluster("Phase 4: Platform"):
        acr = ContainerRegistries("acr.bicep\nContainer Registry")
        aks = KubernetesServices("aks.bicep\nAKS Cluster")
        vm = VM("vm.bicep\nDevOps VM")

    # Dependencies — Phase 1 (no external deps)
    # kv depends on vnet (PE subnet)
    vnet >> Edge(label="PE subnet", style="dashed") >> kv

    # Phase 2 depends on Phase 1
    vnet >> Edge(label="delegated subnet") >> pg
    kv >> Edge(label="secrets") >> pg
    vnet >> Edge(label="PE subnet") >> redis
    vnet >> Edge(label="PE subnet") >> storage
    law >> Edge(label="diagnostics", style="dotted") >> pg
    law >> Edge(label="diagnostics", style="dotted") >> redis
    law >> Edge(label="diagnostics", style="dotted") >> storage

    # PEs connect to data services
    pg >> Edge(style="dashed") >> pe
    redis >> Edge(style="dashed") >> pe
    kv >> Edge(style="dashed") >> pe
    storage >> Edge(style="dashed") >> pe

    # Phase 3 depends on Phase 1 + 2
    vnet >> Edge(label="APIM subnet") >> apim
    kv >> Edge(label="certificates") >> apim
    apim >> Edge(label="origin") >> fd
    law >> Edge(label="diagnostics", style="dotted") >> apim
    law >> Edge(label="diagnostics", style="dotted") >> fd

    # Phase 4 depends on Phase 1 + 2 + 3
    vnet >> Edge(label="AKS subnet") >> aks
    kv >> Edge(label="secrets") >> aks
    acr >> Edge(label="image pull") >> aks
    law >> Edge(label="monitoring") >> aks
    vnet >> Edge(label="VM subnet") >> vm
    kv >> Edge(label="secrets") >> vm
    law >> Edge(label="diagnostics", style="dotted") >> vm
