"""
04-runtime-diagram.py — Runtime request/auth/event flow for Contoso Service Hub.
Generated by bicep-plan agent | 2026-03-17
"""

from diagrams import Diagram, Cluster, Edge
from diagrams.azure.compute import KubernetesServices, VirtualMachinesClassic as VM, ContainerRegistries
from diagrams.azure.database import DatabaseForPostgresqlServers as DatabaseForPostgreSQL, CacheForRedis
from diagrams.azure.network import FrontDoors, ApplicationGateway
from diagrams.azure.security import KeyVaults
from diagrams.azure.storage import StorageAccounts
from diagrams.azure.analytics import LogAnalyticsWorkspaces
from diagrams.azure.devops import ApplicationInsights
from diagrams.azure.identity import ExternalIdentities
from diagrams.onprem.client import Users

graph_attr = {
    "fontsize": "16",
    "bgcolor": "white",
    "pad": "0.5",
    "rankdir": "TB",
    "dpi": "150",
}

edge_attr_request = {"color": "#2196F3", "penwidth": "2.0"}
edge_attr_auth = {"color": "#FF9800", "penwidth": "2.0", "style": "dashed"}
edge_attr_secret = {"color": "#9C27B0", "penwidth": "1.5", "style": "dotted"}
edge_attr_telemetry = {"color": "#4CAF50", "penwidth": "1.0", "style": "dotted"}

with Diagram(
    "Contoso Service Hub — Runtime Flow",
    filename="agent-output/contoso-service-hub-run-3/04-runtime-diagram",
    show=False,
    direction="TB",
    graph_attr=graph_attr,
    outformat="png",
):
    users = Users("End Users\n(5K–15K)")

    with Cluster("Edge Layer"):
        fd = FrontDoors("Front Door Premium\n+ WAF (OWASP 3.2)")

    with Cluster("Identity"):
        entra = ExternalIdentities("Entra External ID\n(CIAM, MFA)")

    with Cluster("API Gateway"):
        apim = ApplicationGateway("APIM\n(Internal VNet)")

    with Cluster("Compute Layer"):
        aks = KubernetesServices("AKS Cluster\n3×D8s_v5\n(15 microservices)")

    with Cluster("Data Layer"):
        pg = DatabaseForPostgreSQL("PostgreSQL Flex\n8 vCores, 256 GB")
        redis = CacheForRedis("Redis Premium P4\n53 GB (sessions)")
        storage = StorageAccounts("Storage (ZRS)\nBlob + Files")

    with Cluster("Security"):
        kv = KeyVaults("Key Vault\n(secrets, certs)")

    with Cluster("Observability"):
        law = LogAnalyticsWorkspaces("Log Analytics\n5 GB/day")
        ai = ApplicationInsights("App Insights\n(distributed tracing)")

    # Request flow (blue)
    users >> Edge(label="HTTPS", **edge_attr_request) >> fd
    fd >> Edge(label="Route", **edge_attr_request) >> apim
    apim >> Edge(label="API calls", **edge_attr_request) >> aks
    aks >> Edge(label="CRUD", **edge_attr_request) >> pg
    aks >> Edge(label="Cache R/W", **edge_attr_request) >> redis
    aks >> Edge(label="Blob/File I/O", **edge_attr_request) >> storage

    # Auth flow (orange dashed)
    users >> Edge(label="OAuth 2.0 / OIDC", **edge_attr_auth) >> entra
    entra >> Edge(label="Token", **edge_attr_auth) >> apim
    apim >> Edge(label="JWT validation", **edge_attr_auth) >> aks

    # Secret flow (purple dotted)
    kv >> Edge(label="conn strings", **edge_attr_secret) >> aks
    kv >> Edge(label="certs", **edge_attr_secret) >> apim
    kv >> Edge(label="keys", **edge_attr_secret) >> pg

    # Telemetry flow (green dotted)
    aks >> Edge(label="traces", **edge_attr_telemetry) >> ai
    apim >> Edge(label="logs", **edge_attr_telemetry) >> law
    fd >> Edge(label="access logs", **edge_attr_telemetry) >> law
    pg >> Edge(label="diagnostics", **edge_attr_telemetry) >> law
    redis >> Edge(label="metrics", **edge_attr_telemetry) >> law
    ai >> Edge(label="linked", **edge_attr_telemetry) >> law
