// Auto-generated by tools/scripts/scaffold-trigger-tests.mjs.
// Source of truth: tests/azure-rbac/trigger_tests.yaml
// Re-run the scaffolder after editing the YAML.
//
// This shim exists so the sensei GEPA auto-evaluator
// (.github/skills/sensei/scripts/src/gepa/auto_evaluator.py) can
// discover trigger arrays via its regex-based parser.

export const shouldTriggerPrompts: string[] = [
  "what role should I assign",
  "How do I what role should I assign?",
  "What role should I assign now",
  "what role should I assign for my project",
  "least privilege role",
  "How do I least privilege role?",
  "Least privilege role now",
  "least privilege role for my project",
  "RBAC role for",
  "How do I RBAC role for?",
  "RBAC role for now",
  "RBAC role for for my project",
  "role for managed identity",
  "How do I role for managed identity?",
  "Role for managed identity now",
  "role for managed identity for my project",
  "custom role definition",
  "How do I custom role definition?",
  "Custom role definition now",
  "custom role definition for my project",
  "assign role to identity",
  "How do I assign role to identity?",
  "Assign role to identity now",
  "assign role to identity for my project",
  "role discovery",
  "How do I role discovery?",
  "Role discovery now",
  "role discovery for my project",
  "RBAC scaffolding",
  "How do I RBAC scaffolding?",
  "RBAC scaffolding now",
  "RBAC scaffolding for my project",
  "least-privilege analysis",
  "How do I least-privilege analysis?",
  "Least-privilege analysis now",
  "least-privilege analysis for my project",
];

export const shouldNotTriggerPrompts: string[] = [
  "deploying resources",
  "How do I deploying resources?",
  "security audits",
  "How do I security audits?",
  "use azure-deploy",
  "run azure-deploy",
  "use azure-compliance",
  "run azure-compliance",
  "What is the weather today?",
  "Help me write a poem",
];
